### ISSUE TITLE
Guns Won't Fire when Pointed to the Sky

### ISSUE THREAD

**Issue by TwiliDiamondOcelot** [FlansMods/FlansMod#1100] opened 2019-07-31 23:08 UTC
**Describe the bug**
When you try to fire a gun into the sky, the gun does the shooting animation but nothing happens.

**To Reproduce**
Steps to reproduce the behaviour:
1. Get ANY gun.
2. Shoot the sky.

**Expected behaviour**
The gun should fire.

**Versions**
 - Forge: 14.23.5.2837
 - Flan's Mod: 5.6

**Comment by Liruxo** [comment] 2019-08-02 18:20
Please clarify "The gun should fire", as i am unable to see the problem. The gun has a shooting animation, it has recoil and it uses ammo when pointed at the sky and fired. There is a know issue #1022 with the gun trail, but that is all i know.

**Comment by syncromash** [comment] 2019-08-04 20:20
do they fire normally?

**Comment by TwiliDiamondOcelot** [comment] 2019-08-05 03:02
![ezgif com-optimize](https://user-images.githubusercontent.com/53383686/62435936-f2f24e00-b70b-11e9-9313-446a064ea6fa.gif)

**Comment by syncromash** [comment] 2019-08-05 05:18
Ah I see I thought you meant tank guns as they are currently broken

Sent from my iPhone

On 5 Aug 2019, at 04:02, TwiliDiamondOcelot <notifications@github.com<mailto:notifications@github.com>> wrote:


[ezgif com-optimize]<https://user-images.githubusercontent.com/53383686/62435936-f2f24e00-b70b-11e9-9313-446a064ea6fa.gif>

**Comment by Liruxo** [comment] 2019-08-05 09:29
I am unable to reproduce this behavior in the latest release of FlansMod, v5.6-beta.5
Please check that you are running the latest version of the Content Packs and FlansMod and make sure to test this without other mods installed.

**Comment by syncromash** [comment] 2019-08-05 09:52
I downloaded the latest patch and latest flansmod

Sent from my iPhone

On 5 Aug 2019, at 10:29, Liruxo <notifications@github.com<mailto:notifications@github.com>> wrote:


I am unable to reproduce this behavior in the latest release of FlansMod, v5.6-beta.5
Please check that you are running the latest version of the Content Packs and FlansMod and make sure to test this without other mods installed.

**Comment by syncromash** [comment] 2019-08-05 09:52
Oh sorry this is the wrong issue this works fine on my computer I was talking about tank guns not firing

Sent from my iPhone

On 5 Aug 2019, at 10:29, Liruxo <notifications@github.com<mailto:notifications@github.com>> wrote:


I am unable to reproduce this behavior in the latest release of FlansMod, v5.6-beta.5
Please check that you are running the latest version of the Content Packs and FlansMod and make sure to test this without other mods installed.

**Comment by TwiliDiamondOcelot** [comment] 2019-08-05 14:19
Ok, yeah, it works without other mods so I'm going to add them one by one now and see which one it is.

**Comment by TwiliDiamondOcelot** [comment] 2019-08-05 15:18
Found the mod causing problems. This happens when MalisisCore is installed.
https://www.curseforge.com/minecraft/mc-mods/malisiscore

**Comment by ChrisLane** [comment] 2019-08-06 07:57
Since MalasisCore is a core mod and the issue isn't present without it, I'm going to close this issue for now.
Please try to get in contact with the devs of the mod.

**Closed as completed by ChrisLane** 2019-08-06 07:57 UTC
Labels: bug
