### ISSUE TITLE
Spawning in Flans Mod Entities Crashes Me

### ISSUE THREAD

**Issue by LilShrimp01** [FlansMods/FlansMod#816] opened 2016-06-14 21:44 UTC
Whilst playing on my modded single player world, I wanted to spawn in a vehicle from Flans mod, but when I right clicked the ground with the vehicle item it crashed my game. I have the latest Forge and I am using Flans+ Mod, an updated graphic card, and updated Java. Now, keep in mind that this wasn't happening before. Previously, before I had to reinstall Minecraft (long story on why I had to do that), Flans+ mod and the content packs I installed coexisted, and I never had an crashes. Now I do for some reason! Please help!
-------------------------------------------------------------------------------------------------------------------------------

---- Minecraft Crash Report ----
// Oops.

Time: 6/14/16 3:40 PM
Description: Ticking memory connection

java.lang.NullPointerException: Ticking memory connection
	at com.flansmod.common.driveables.DriveableType.getDriveable(DriveableType.java:732)
	at com.flansmod.common.driveables.DriveableData.readFromNBT(DriveableData.java:48)
	at com.flansmod.common.driveables.DriveableData.<init>(DriveableData.java:37)
	at com.flansmod.common.driveables.ItemVehicle.getData(ItemVehicle.java:176)
	at com.flansmod.common.driveables.ItemVehicle.func_77659_a(ItemVehicle.java:142)
	at net.minecraft.item.ItemStack.func_77957_a(ItemStack.java:146)
	at net.minecraft.server.management.ItemInWorldManager.func_73085_a(ItemInWorldManager.java:316)
	at net.minecraft.network.NetHandlerPlayServer.func_147346_a(NetHandlerPlayServer.java:539)
	at net.minecraft.network.play.client.C08PacketPlayerBlockPlacement.func_148833_a(SourceFile:60)
	at net.minecraft.network.play.client.C08PacketPlayerBlockPlacement.func_148833_a(SourceFile:9)
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212)
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:186)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at com.flansmod.common.driveables.DriveableType.getDriveable(DriveableType.java:732)
	at com.flansmod.common.driveables.DriveableData.readFromNBT(DriveableData.java:48)
	at com.flansmod.common.driveables.DriveableData.<init>(DriveableData.java:37)
	at com.flansmod.common.driveables.ItemVehicle.getData(ItemVehicle.java:176)
	at com.flansmod.common.driveables.ItemVehicle.func_77659_a(ItemVehicle.java:142)
	at net.minecraft.item.ItemStack.func_77957_a(ItemStack.java:146)
	at net.minecraft.server.management.ItemInWorldManager.func_73085_a(ItemInWorldManager.java:316)
	at net.minecraft.network.NetHandlerPlayServer.func_147346_a(NetHandlerPlayServer.java:539)
	at net.minecraft.network.play.client.C08PacketPlayerBlockPlacement.func_148833_a(SourceFile:60)
	at net.minecraft.network.play.client.C08PacketPlayerBlockPlacement.func_148833_a(SourceFile:9)
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212)

-- Ticking connection --
Details:
	Connection: net.minecraft.network.NetworkManager@65ab81df
Stacktrace:
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:186)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 223861088 bytes (213 MB) / 1060372480 bytes (1011 MB) up to 1060372480 bytes (1011 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1614 Optifine OptiFine_1.7.10_HD_U_C1 14 mods loaded, 14 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{7.10.99.99} [Forge Mod Loader] (forge-1.7.10-10.13.4.1614-1.7.10.jar) 
	UCHIJAAAA	Forge{10.13.4.1614} [Minecraft Forge] (forge-1.7.10-10.13.4.1614-1.7.10.jar) 
	UCHIJAAAA	BiomesOPlenty{2.1.0} [Biomes O' Plenty] (BiomesOPlenty-1.7.10-2.1.0.1396-universal.jar) 
	UCHIJAAAA	chisel{2.9.5.11} [Chisel] (Chisel-2.9.5.11.jar) 
	UCHIJAAAA	CarpentersBlocks{3.3.8} [Carpenter's Blocks] (Carpenter's Blocks v3.3.8 - MC 1.7.10.jar) 
	UCHIJAAAA	customnpcs{1.7.10d} [CustomNpcs] (CustomNPCs_1.7.10d(21feb16).jar) 
	UCHIJAAAA	flansmod{4.10.0} [Flan's Mod] (Flans Mod Plus-1.7.10-4.10.0-1.0.3.jar) 
	UCHIJAAAA	MapWriter{2.1.1} [MapWriter] (Flans Mod Plus-1.7.10-4.10.0-1.0.3.jar) 
	UCHIJAAAA	IC2{2.2.822-experimental} [IndustrialCraft 2] (industrialcraft-2-2.2.822-experimental.jar) 
	UCHIJAAAA	journeymap{@JMVERSION@} [JourneyMap] (journeymap-1.7.10-5.1.0-unlimited.jar) 
	UCHIJAAAA	mcheli{1.0.2} [MC Helicopter] (mcheli) 
	UCHIJAAAA	warstuff{1.4} [WarStuff] (warstuff-1.4.jar) 
	UCHIJAAAA	worldedit{6.0-beta-01} [WorldEdit] (worldedit-forge-mc1.7.10-6.0-beta-01.jar) 
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	Chisel: Errors like "[FML]: Unable to lookup ..." are NOT the cause of this crash. You can safely ignore these errors. And update forge while you're at it.
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Player Count: 1 / 8; [EntityPlayerMP['LilShrimp01'/36, l='Ambircon', x=535.64, y=4.00, z=1612.36]]
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'

**Comment by ChrisLane** [comment] 2016-06-26 22:42
What content packs are you using?
Does this happen every time you place any vehicle on any map or is it a specific vehicle?

**Comment by ChrisLane** [comment] 2016-06-27 00:55
Dupe of #815

**Closed by ChrisLane** 2016-06-27 00:55 UTC
Labels: Crash

**Comment by LilShrimp01** [comment] 2016-06-27 01:31
I have all the base content packs-Simple Parts pack and the SMP Parts pack. I have no other mods except Flans+. Also, I tried it with regular Flans Mod version 4.10 and the vehicles still crash when I spawn them. Some vehicles work, but when I spawn them in they make a weird gun sound for some reason. I also want to state that this wasn't happening before and that all the content packs I was using before were working, this only started happening after I reinstalled Minecraft.

**Comment by LilShrimp01** [comment] 2016-06-27 01:35
All the content packs I have are 1.7.10, Flans is 1.7.10, and Forge 1.7.10 is updated to the latest.

**Comment by LilShrimp01** [comment] 2016-06-27 01:40
I have tried 1.8 Flans Mod, and it works fine with no crashes (but some models lag because I have a crap laptop). But being that a lot of the good content packs aren't 1.8 yet, except for the jamioFlan packs, and a lot of the good mods out there are 1.7.10 and not updated to 1.8, I cannot update to 1.7.10 ;-;

**Comment by LilShrimp01** [comment] 2016-06-27 01:45
I can also confirm this is not a dupe of the 815 issue because A) Not all the packs have the "DS_Store files" and B) Even the "DS_Store files" that I delete for those that have it still lead to a crash.

**Comment by ChrisLane** [comment] 2016-06-27 11:08
DS_Store files shouldn't be causing the issue, the error is the same as the other issue.

Please see if you can replicate this issue with only Flan's Mod official content packs and take respond on the other issue.

**Comment by LilShrimp01** [comment] 2016-06-27 14:52
Ok
