### ISSUE TITLE
EntitySeat crash

### ISSUE THREAD

**Issue by XakepSDK** [FlansMods/FlansMod#739] opened 2015-09-04 16:23 UTC
---- Minecraft Crash Report ----
// I let you down. Sorry :(

Time: 9/4/15 6:34 PM
Description: Ticking entity

java.lang.ArrayIndexOutOfBoundsException: 0
        at com.flansmod.common.driveables.EntitySeat.pressKey(EntitySeat.java:431)
        at com.flansmod.common.driveables.EntitySeat.func_70071_h_(EntitySeat.java:179)
        at net.minecraft.world.World.func_72866_a(World.java:2655)
        at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:837)
        at net.minecraft.world.World.func_72870_g(World.java:2607)
        at net.minecraft.world.World.func_72939_s(World.java:2423)
        at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:669)
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:954)
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:431)
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:809)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:669)
        at java.lang.Thread.run(Thread.java:745)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
        at com.flansmod.common.driveables.EntitySeat.pressKey(EntitySeat.java:431)
        at com.flansmod.common.driveables.EntitySeat.func_70071_h_(EntitySeat.java:179)
        at net.minecraft.world.World.func_72866_a(World.java:2655)
        at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:837)
        at net.minecraft.world.World.func_72870_g(World.java:2607)

-- Entity being ticked --
Details:
        Entity Type: Seat (com.flansmod.common.driveables.EntitySeat)
        Entity ID: 34503
        Entity Name: entity.Seat.name
        Entity's Exact location: -4177.14, 77.75, 2578.30
        Entity's Block location: World: (-4178,77,2578), Chunk: (at 14,4,2 in -262,161; contains blocks -4192,0,2576 to -4177,255,2591), Region: (-9,5; contains chunks -288,160 to -257,191, blocks -4608,0,2560 to -4097,255,3071)
        Entity's Momentum: 0.00, 0.00, 0.00
Stacktrace:
        at net.minecraft.world.World.func_72939_s(World.java:2423)
        at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:669)

-- Affected level --
Details:
        Level name: world
        All players: 3 total; [EntityPlayerMP['xAltron'/34079, l='world', x=-4177.20, y=77.25, z=2577.56](xAltron at -4177.19564180437,77.2502738237381,2577.5561432272398), EntityPlayerMP['ZeFFiR_SDK'/34240, l='world', x=-4450.09, y=62.20, z=3811.70](ZeFFiR_SDK at -4450.092206834024,62.200000047683716,3811.699999988079), EntityPlayerMP['xVillain1'/34466, l='world', x=-4177.14, y=77.25, z=2578.30](xVillain1 at -4177.140573877725,77.2502738237381,2578.3041188150846)]
        Chunk stats: ServerChunkCache: 916 Drop: 0
        Level seed: 5987405545015902063
        Level generator: ID 00 - default, ver 1. Features enabled: true
        Level generator options:
        Level spawn location: World: (-4447,60,3808), Chunk: (at 1,3,0 in -278,238; contains blocks -4448,0,3808 to -4433,255,3823), Region: (-9,7; contains chunks -288,224 to -257,255, blocks -4608,0,3584 to -4097,255,4095)
        Level time: 69776782 game time, 49592901 day time
        Level dimension: 0
        Level storage version: 0x04ABD - Anvil
        Level weather: Rain time: 21363 (now: false), thunder time: 116007 (now: false)
        Level game mode: Game mode: adventure (ID 2). Hardcore: false. Cheats: true
Stacktrace:
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:954)
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:431)
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:809)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:669)
        at java.lang.Thread.run(Thread.java:745)

-- System Details --
Details:
        Minecraft Version: 1.7.10
        KCauldron Version: pw.prok:KCauldron:1.7.10-1481.145
        Operating System: Linux (amd64) version 3.10.0-229.11.1.el7.x86_64
        Java Version: 1.8.0_51, Oracle Corporation
        Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Oracle Corporation
        Memory: 872759104 bytes (832 MB) / 2053636096 bytes (1958 MB) up to 3817865216 bytes (3641 MB)
        JVM Flags: 2 total; -Xms1G -Xmx4G
        AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
        IntCache: cache: 0, tcache: 0, allocated: 12, tallocated: 94
        FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1481 13 mods loaded, 13 mods active
        States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
        UCHIJAAAA       mcp{9.05} [Minecraft Coder Pack] (minecraft.jar)
        UCHIJAAAA       FML{7.10.99.99} [Forge Mod Loader] (KCauldron.jar)
        UCHIJAAAA       Forge{10.13.4.1481} [Minecraft Forge] (KCauldron.jar)
        UCHIJAAAA       kimagine{0.1} [KImagine] (minecraft.jar)
        UCHIJAAAA       CodeChickenCore{1.0.4.29} [CodeChicken Core] (minecraft.jar)
        UCHIJAAAA       NotEnoughItems{1.0.3.64} [Not Enough Items] (NotEnoughItems.jar)
        UCHIJAAAA       PlayerAPI{1.3} [Player API] (minecraft.jar)
        UCHIJAAAA       SmartCore{1.0} [Smart Core] (minecraft.jar)
        UCHIJAAAA       customnpcs{1.7.10b} [CustomNpcs] (CustomNPCs_1.7.10b.jar)
        UCHIJAAAA       flansmod{4.10.0} [Flan's Mod] (Flan's Mod-1.7.10-4.10.0.jar)
        UCHIJAAAA       SmartMoving{15.2} [Smart Moving] (SmartMoving.jar)
        UCHIJAAAA       SmartRender{2.0} [Smart Render] (SmartRender.jar)
        UCHIJAAAA       stalkermod{0.1} [S.T.A.L.K.E.R Mod] (STALKER_mod-0.1.jar)
        Profiler Position: N/A (disabled)
        Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
        Player Count: 3 / 50; [EntityPlayerMP['xAltron'/34079, l='world', x=-4177.20, y=77.25, z=2577.56](xAltron at -4177.19564180437,77.2502738237381,2577.5561432272398), EntityPlayerMP['ZeFFiR_SDK'/34240, l='world', x=-4450.09, y=62.20, z=3811.70](ZeFFiR_SDK at -4450.092206834024,62.200000047683716,3811.699999988079), EntityPlayerMP['xVillain1'/34466, l='world', x=-4177.14, y=77.25, z=2578.30](xVillain1 at -4177.140573877725,77.2502738237381,2578.3041188150846)]
        Is Modded: Definitely; Server brand changed to 'kcauldron,cauldron,craftbukkit,mcpc,fml,forge'
        Type: Dedicated Server (map_server.txt)

Nothing changed. This is already fixed(what commit?)? Or still not fixed? I can use only 1.7.10....

**Comment by XakepSDK** [comment] 2015-09-04 16:25
Forgot to add:
Flans mods:
manus_dayz_package_1.7.10d_for_flan_4.8.1.zip
minecraft-smp_parts_package-content_pack-1.7.10a-4.10.0.jar
Modern Warfare-Content Pack-1.7.10-4.10.0.jar
Simple Parts-Content Pack-1.7.10-4.10.0.jar

**Comment by XakepSDK** [comment] 2015-09-04 17:46
Found ways, to crash:
Press escape(main menu)
Then exit and very fast press LMB and RMB

**Comment by XakepSDK** [comment] 2015-09-04 17:48
Bad code:
        if (riddenByEntity instanceof EntityPlayer && shooting) {
            pressKey(9, (EntityPlayer) riddenByEntity);
        }
LMB not need.

**Comment by XakepSDK** [comment] 2015-09-04 17:58
manus_dayz_package_1.7.10d_for_flan_4.8.1.zip
crashes server.
Another cars/planes(all vehicles from mw pack) don't crash the server.
Where can i download source code for this mod? Or download for flans 4.10.

**Comment by ChrisLane** [comment] 2016-06-27 00:28
This should be checked in the mod but is also an issue caused by a

**Closed by ChrisLane** 2016-06-27 00:28 UTC
