### ISSUE TITLE
[1.12.2] 5.6 Beta "[Flansmod]: Killing wheel due to invalid type tag"

### ISSUE THREAD

**Issue by emilwalseth** [FlansMods/FlansMod#977] opened 2018-12-09 13:39 UTC
Hey!
I am running the Beta 5.6 for 1.12.2 on my spongepowered server.

When i place and fly certain planes, it suddenly dissapears mid-air.
Console says: "[Flansmod]: Killing wheel due to invalid type tag"

Can i do something about it

**Comment by ChrisLane** [comment] 2018-12-10 20:36
Duplicate of #974

**Closed as completed by ChrisLane** 2018-12-10 20:36 UTC
