### ISSUE TITLE
[v5.6-beta.2] Secondary gun not working on planes.

### ISSUE THREAD

**Issue by ghost** [FlansMods/FlansMod#999] opened 2019-01-29 17:39 UTC
There is an issue with drivers secondary weapons.
E.g of it, main armaments work (missiles, tank cannons etc) but guns like aircraft's main guns (e.g minigun on a-10, drivers guns on ww2 aircraft) do not work. Also, guns that are controlled by another player for example the minigun on the cobra works fine.

Get a vehicle such as A-10, spitfire, bf109 and much more and load the gun slots
Try to fire it
Doesn't work
The weapons are supposed to fire as normal, e.g minigun on a-10 should fire as a minigun.

Forge: 1.12.2 - 14.23.5.2768
Flan's Mod: v5.6-beta.2
Any insight into this issue will be appreciated, thanks.

**Comment by ChrisLane** [comment] 2019-01-29 20:11
Duplicate of #910

**Closed as completed by ChrisLane** 2019-01-29 20:11 UTC
Labels: bug
