### ISSUE TITLE
ArrayIndexOutOfBoundsException in EntityBullet

### ISSUE THREAD

**Issue by BlackJack55** [FlansMods/FlansMod#621] opened 2014-12-15 20:07 UTC
java.lang.ArrayIndexOutOfBoundsException: -11
at com.flansmod.common.guns.EntityBullet.func_70071_h_(EntityBullet.java:284) ~[EntityBullet.class:?]
at net.minecraft.world.World.func_72866_a(World.java:2610) ~[ahb.class:?]
at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:834) ~[mt.class:?]
at net.minecraft.world.World.func_72870_g(World.java:2563) ~[ahb.class:?]
at net.minecraft.world.World.func_72939_s(World.java:2375) ~[ahb.class:?]
at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:665) ~[mt.class:?]
at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:937) ~[MinecraftServer.class:?]
at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:422) ~[lt.class:?]
at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:803) ~[MinecraftServer.class:?]
at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:663) [MinecraftServer.class:?]
at java.lang.Thread.run(Thread.java:745) [?:1.7.0_72]

Happened around 10 times already

This is happening on the server.

**Comment by ChrisLane** [comment] 2016-06-27 00:06
Haven't seen this for a long time. Assuming fixed in more recent versions.

**Closed by ChrisLane** 2016-06-27 00:06 UTC
Labels: Bug

**Comment by KsenMih** [comment] 2017-02-23 14:48
Hi @ChrisLane,

Sorry for re-opening this issue, but my server keep randomly crashing with the same error. It seems to happen sometimes when a player use a gun. I don't have any more informations about this :/

**Forge version :** 7.99.4.1614 (MC: 1.7.10)
**Flan's Mod version :** 4.10.0
**Content(s) pack(s) :** Dutch KCT-4.7.0
**Server platform :**  Thermos b58 | 1.7.10-R0.1-SNAPSHOT | 1.7.10-1614.58 (MC: 1.7.10)
**Error message (from console) :** http://pastebin.com/raw/1vwuv009
**Error message (from crash-reports) :** http://pastebin.com/raw/BDW6pzkY

> [15:20:40] [Server thread/ERROR]: Encountered an unexpected exception
net.minecraft.util.ReportedException: Ticking entity
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:1003) ~[MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:432) ~[lt.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:841) ~[MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:693) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]
Caused by: java.lang.ArrayIndexOutOfBoundsException: -18982
        at com.flansmod.common.guns.EntityBullet.func_70071_h_(EntityBullet.java:284) ~[EntityBullet.class:?]
        at net.minecraft.world.World.func_72866_a(World.java:2740) ~[ahb.class:?]
        at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:877) ~[mt.class:?]
        at net.minecraft.world.World.func_72870_g(World.java:2678) ~[ahb.class:?]
        at net.minecraft.world.World.func_72939_s(World.java:2480) ~[ahb.class:?]
        at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:673) ~[mt.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:986) ~[MinecraftServer.class:?]
        ... 4 more
[15:20:40] [Server thread/ERROR]:       Cause of unexpected exception was
java.lang.ArrayIndexOutOfBoundsException: -18982
        at com.flansmod.common.guns.EntityBullet.func_70071_h_(EntityBullet.java:284) ~[EntityBullet.class:?]
        at net.minecraft.world.World.func_72866_a(World.java:2740) ~[ahb.class:?]
        at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:877) ~[mt.class:?]
        at net.minecraft.world.World.func_72870_g(World.java:2678) ~[ahb.class:?]
        at net.minecraft.world.World.func_72939_s(World.java:2480) ~[ahb.class:?]
        at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:673) ~[mt.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:986) ~[MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:432) ~[lt.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:841) ~[MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:693) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]

Tell me if you need more informations about the map, chunks where the problem occurs, logs, crash reports, etc... Anyway, thanks in advance if someone can take a look to this, or find a fix.
