### ISSUE TITLE
Looked Stopping

### ISSUE THREAD

**Issue by ym1025** [FlansMods/FlansMod#1173] opened 2020-02-18 09:01 UTC
**To Reproduce**
Steps to reproduce the crash:
1. Fire any gun
2. Looked "Time-stopping"
3. MC crashed
4. I can't load the world

**Screenshots**

**Versions (please complete the following information)**
 - Forge: 2847
 - Flan's Mod:5.6-beta6 

**Crash Log**

https://gist.github.com/ym1025/7804378709fdd011e558a70600d4c4cc
**Additional context**

**Comment by ym1025** [comment] 2020-02-18 09:27
I made different world, but MC has crashed too.

**Comment by StargateMC** [comment] 2020-02-22 15:30
Also seeing this whenever any weapons fired on Beta 6.

`---- Minecraft Crash Report ----

WARNING: coremods are present:
  CoreMod (TickProfiler-0.0.7.jar)
  ForgelinPlugin (Forgelin-1.8.4.jar)
  AdvancedRocketryPlugin (AdvancedRocketry-1.6.0z100.jar)
  Inventory Tweaks Coremod (InventoryTweaks-1.6.3.jar)
  RandomPatches (RandomPatches-1.121.0.0.jar)
  MalisisCorePlugin (MalisisCore-6.5.1b.jar)
  TransformerLoader (OpenComputers-1.7.5.192.jar)
  IELoadingPlugin (ImmersiveEngineering-core-0.12-92.jar)
  LoadingPlugin (ChunkAnimator-1.2.jar)
  IvToolkit (IvToolkit-1.3.3.jar)
  SoundUnpack (OpenSecurity-1.0.39.jar)
  CTMCorePlugin (CTM-1.0.1.30.jar)
  MekanismCoremod (Mekanism-9.8.3.390.jar)
Contact their authors BEFORE contacting forge

// But it works on my machine.

Time: 2/22/20 3:00 PM
Description: Exception in server tick loop

java.lang.StackOverflowError: Exception in server tick loop
        at java.io.UnixFileSystem.canonicalize0(Native Method)
        at java.io.UnixFileSystem.canonicalize(UnixFileSystem.java:172)
        at java.io.File.getCanonicalPath(File.java:618)
        at java.io.FilePermission$1.run(FilePermission.java:248)
        at java.io.FilePermission$1.run(FilePermission.java:236)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.io.FilePermission.init(FilePermission.java:236)
        at java.io.FilePermission.<init>(FilePermission.java:310)
        at java.lang.SecurityManager.checkRead(SecurityManager.java:888)
        at java.io.File.exists(File.java:814)
        at net.minecraft.world.chunk.storage.RegionFile.<init>(RegionFile.java:41)
        at net.minecraft.world.chunk.storage.RegionFileCache.func_76550_a(SourceFile:64)
        at net.minecraft.world.chunk.storage.RegionFileCache.func_76549_c(SourceFile:110)
        at net.minecraft.world.chunk.storage.AnvilChunkLoader.loadChunk__Async(AnvilChunkLoader.java:82)
        at net.minecraftforge.common.chunkio.ChunkIOProvider.run(ChunkIOProvider.java:70)
        at net.minecraftforge.common.chunkio.ChunkIOExecutor.syncChunkLoad(ChunkIOExecutor.java:92)
        at net.minecraft.world.gen.ChunkProviderServer.loadChunk(ChunkProviderServer.java:118)
        at net.minecraft.world.gen.ChunkProviderServer.func_186028_c(ChunkProviderServer.java:89)
        at net.minecraft.world.gen.ChunkProviderServer.func_186025_d(ChunkProviderServer.java:135)
        at net.minecraft.world.World.func_72964_e(World.java:310)
        at net.minecraft.world.World.func_175726_f(World.java:305)
        at net.minecraft.world.World.func_180495_p(World.java:911)
        at com.flansmod.common.guns.raytracing.FlansModRaytracer.raytraceBlock(FlansModRaytracer.java:184)`

**Comment by ChrisLane** [comment] 2020-08-16 18:28
This crash was caused by malassis core and is fixed in recent versions.

**Closed as completed by ChrisLane** 2020-08-16 18:28 UTC
Labels: crash
