### ISSUE TITLE
[1.12][bug] screen goes black when pressing f1, f5, or holding a model with Modular Machines installed.

### ISSUE THREAD

**Issue by mensreaMC** [FlansMods/FlansMod#959] opened 2018-10-15 13:08 UTC
as the title says, if you have flans and modular machines installed the screen will go black if you press f1, f5, or hold a model. you can see some GUI elements but otherwise the entire background is totally. might be an issue because a lot of packs are using modular machines these days.

**Comment by mr2meowsYT** [comment] 2019-01-26 14:13
(i do not have modular machines) i have that issue too with f5 (1.8 n stuff does not have that problem because on youtube TheAtlanticraft uses flans mod and halocraft (halocraft is 1.8.9 only) and they use f5 also if u use security craft cams the screen goes black yeet )

**Comment by ChrisLane** [comment] 2019-01-28 08:54
Can you please provide more information:
- Does this occur with the latest version of Flan's Mod and Forge?
- Which single mods cause this behaviour with Flan's Mod?
- Please provide a paste of a client log when you've reproduced this
- Please provide a screenshot of the issue.

**Comment by mensreaMC** [comment] 2019-07-04 00:56
-Occurs with the most recent build of flans from this github and the latest forge (version 14.23.5.2838)
-Any version of modular machinery past version 1.7.1
-[latest.log](https://github.com/FlansMods/FlansMod/files/3357227/latest.log)
-
![screenshot 1](https://user-images.githubusercontent.com/1071401/60632682-06d92600-9dd5-11e9-81af-ba52228da071.png)
![screenshot 2](https://user-images.githubusercontent.com/1071401/60632683-093b8000-9dd5-11e9-8cd2-8327509f4dda.png)

**Comment by mensreaMC** [comment] 2019-08-16 03:34
So I thought I'd mention that I tried updating MM today and this issue is now seemingly resolved! 1.11.1 or another recent patch must have fixed it. Thanks to everyone involved for your help.

**Comment by ChrisLane** [comment] 2019-08-19 07:58
🎉 
Thanks for keeping this updated :)

**Comment by mensreaMC** [comment] 2019-09-07 05:46
Bad news: it turns out it was actually something with Optifine that was fixing this bug. I removed Optifine and the bug was still present.

**Comment by Liruxo** [comment] 2019-09-07 06:37
Then you should reopen the bug

**Comment by Liruxo** [comment] 2019-09-15 21:27
This was fixed in 751024d. Any future release should not contain this bug

**Closed as completed** 2020-08-28 08:37 UTC
Labels: bug
