### ISSUE TITLE
Plane not shooting

### ISSUE THREAD

**Issue by roland3564** [FlansMods/FlansMod#1090] opened 2019-07-26 09:09 UTC
**Describe the bug**

**To Reproduce**
Steps to reproduce the behaviour:
1. spawn the plane
2. get in the plane
3. try to shoot with all the existing key bindings (even with the mouse ones)
4. not shooting

**Expected behaviour**

**Versions (please complete the following information)**
 - Forge: 14.23.5.2838
 - Flan's Mod: 5.5.2
 - Minecraft: 1.12.2

**Additional context**
<!-- No additional context

**Comment by Liruxo** [comment] 2019-07-26 09:26
I believe this is a duplicate of #1037
Anyways, this issue should be resolved in the next version of FlansMod

**Closed as completed** 2019-07-26 09:52 UTC
Labels: bug
