### ISSUE TITLE
Can't shoot guns into the air.

### ISSUE THREAD

**Issue by EmeraldTiger64** [FlansMods/FlansMod#927] opened 2018-07-09 01:28 UTC
Hello. I was in-game and noticed while trying to shoot at flying mobs that I can't just randomly shoot into the air. Is this a feature of the mod now or is it a bug? I am just wondering, because I am confused as to why I can't.

**Comment by ChrisLane** [comment] 2018-10-15 19:56
Couldn't reproduce this issue. Could you confirm that you're using the latest version? Some more details would be great.
Closing for now.

**Closed as completed by ChrisLane** 2018-10-15 19:56 UTC
