### ISSUE TITLE
Flan's Mod: Apocalypse - Killing Enemy Mechas = crash and broken save

### ISSUE THREAD

**Issue by MATkis28** [FlansMods/FlansMod#761] opened 2015-11-15 16:00 UTC
I entered to something like bunker and killed one Mecha then game crashed
Crash Report:

---- Minecraft Crash Report ----

WARNING: coremods are present:
  CCLCorePlugin (CodeChickenLib-1.8-1.1.2.133-universal.jar)
  CodeChickenCorePlugin (CodeChickenCore-1.8-1.0.5.36-universal.jar)
  CCCDeobfPlugin (unknown)
  NEICorePlugin (NotEnoughItems-1.8-1.0.5.104-universal.jar)
Contact their authors BEFORE contacting forge

// Ooh. Shiny.

Time: 15.11.15 16:52
Description: Ticking entity

java.lang.NullPointerException: Ticking entity
	at com.flansmod.common.driveables.DriveableType.getItemsRequired(DriveableType.java:537)
	at com.flansmod.common.driveables.mechas.MechaType.getItemsRequired(MechaType.java:186)
	at com.flansmod.common.driveables.EntityDriveable.killPart(EntityDriveable.java:1246)
	at com.flansmod.common.driveables.EntityDriveable.checkParts(EntityDriveable.java:1220)
	at com.flansmod.common.driveables.EntityDriveable.func_70071_h_(EntityDriveable.java:771)
	at com.flansmod.common.driveables.mechas.EntityMecha.func_70071_h_(EntityMecha.java:507)
	at com.flansmod.apocalypse.common.entity.EntityAIMecha.func_70071_h_(EntityAIMecha.java:57)
	at net.minecraft.world.World.func_72866_a(World.java:1880)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:732)
	at net.minecraft.world.World.func_72870_g(World.java:1850)
	at net.minecraft.world.World.func_72939_s(World.java:1679)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:571)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:704)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:598)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:164)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:478)
	at java.lang.Thread.run(Unknown Source)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at com.flansmod.common.driveables.DriveableType.getItemsRequired(DriveableType.java:537)
	at com.flansmod.common.driveables.mechas.MechaType.getItemsRequired(MechaType.java:186)
	at com.flansmod.common.driveables.EntityDriveable.killPart(EntityDriveable.java:1246)
	at com.flansmod.common.driveables.EntityDriveable.checkParts(EntityDriveable.java:1220)
	at com.flansmod.common.driveables.EntityDriveable.func_70071_h_(EntityDriveable.java:771)
	at com.flansmod.common.driveables.mechas.EntityMecha.func_70071_h_(EntityMecha.java:507)
	at com.flansmod.apocalypse.common.entity.EntityAIMecha.func_70071_h_(EntityAIMecha.java:57)
	at net.minecraft.world.World.func_72866_a(World.java:1880)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:732)
	at net.minecraft.world.World.func_72870_g(World.java:1850)

-- Entity being ticked --
Details:
	Entity Type: AIMecha (com.flansmod.apocalypse.common.entity.EntityAIMecha)
	Entity ID: 423
	Entity Name: Proto Titan
	Entity's Exact location: -599,99, 100,00, 846,36
	Entity's Block location: -600,00,100,00,846,00 - World: (-600,100,846), Chunk: (at 8,6,14 in -38,52; contains blocks -608,0,832 to -593,255,847), Region: (-2,1; contains chunks -64,32 to -33,63, blocks -1024,0,512 to -513,255,1023)
	Entity's Momentum: 0,00, 0,00, 0,00
	Entity's Rider: ~~ERROR~~ NullPointerException: null
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1679)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:571)

-- Affected level --
Details:
	Level name: Apocalypse
	All players: 1 total; [EntityPlayerMP['MATkis28'/361, l='Apocalypse', x=-600,06, y=104,00, z=838,36]]
	Chunk stats: ServerChunkCache: 225 Drop: 0
	Level seed: 4868650383582287026
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: 0,00,0,00,0,00 - World: (0,0,0), Chunk: (at 0,0,0 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 0 game time, 0 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:704)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:598)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:164)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:478)
	at java.lang.Thread.run(Unknown Source)

-- System Details --
Details:
	Minecraft Version: 1.8
	Operating System: Windows 7 (amd64) version 6.1
	Java Version: 1.8.0_45, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1005700896 bytes (959 MB) / 1601105920 bytes (1526 MB) up to 1992294400 bytes (1900 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2000M -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn1000M
	IntCache: cache: 8, tcache: 79, allocated: 1, tallocated: 12
	FML: MCP v9.10 FML v8.0.99.99 Minecraft Forge 11.14.4.1563 7 mods loaded, 7 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.8-11.14.4.1563.jar) 
	UCHIJAAAA	Forge{11.14.4.1563} [Minecraft Forge] (forge-1.8-11.14.4.1563.jar) 
	UCHIJAAAA	CodeChickenCore{1.0.5.36} [CodeChicken Core] (minecraft.jar) 
	UCHIJAAAA	NotEnoughItems{1.0.5.104} [Not Enough Items] (NotEnoughItems-1.8-1.0.5.104-universal.jar) 
	UCHIJAAAA	flansmod{5.1} [Flan's Mod] (Flan's Mod-1.8-5.1.jar) 
	UCHIJAAAA	flansmodapocalypse{1.0} [Flan's Mod: Apocalypse] (Flan's Mod Apocalypse-1.8-1.0.jar) 
	Loaded coremods (and transformers): 
CCLCorePlugin (CodeChickenLib-1.8-1.1.2.133-universal.jar)
  codechicken.lib.asm.ClassHeirachyManager
  codechicken.lib.asm.RenderHookTransformer
CodeChickenCorePlugin (CodeChickenCore-1.8-1.0.5.36-universal.jar)
  codechicken.core.asm.InterfaceDependancyTransformer
  codechicken.core.asm.TweakTransformer
  codechicken.core.asm.DelegatedTransformer
  codechicken.core.asm.DefaultImplementationTransformer
CCCDeobfPlugin (unknown)
  
NEICorePlugin (NotEnoughItems-1.8-1.0.5.104-universal.jar)
  codechicken.nei.asm.NEITransformer
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	Profiler Position: N/A (disabled)
	Player Count: 1 / 8; [EntityPlayerMP['MATkis28'/361, l='Apocalypse', x=-600,06, y=104,00, z=838,36]]
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'

**Comment by gigiandearl** [comment] 2015-11-16 02:10
Yes I get this often too, its a unknown bug that should be addressed

**Comment by ChrisLane** [comment] 2016-06-27 00:59
Dupe of #786 now fixed.

**Closed by ChrisLane** 2016-06-27 00:59 UTC
