### ISSUE TITLE
Ray Tracing Error (Loop?) Crash On Server

### ISSUE THREAD

**Issue by EsotericRyoushi** [FlansMods/FlansMod#1238] opened 2020-06-03 04:47 UTC
1.12.2
Flans Mod 5.6 Beta 7

crash happened while shooting at a crab added in from another mod, and the same error occurred when shooting a slime from a different mod. Seems to work sometimes, but not all the time?

Any other information needed, lemme know. sorry, first time Git user. 

https://gist.github.com/EsotericRyoushi/e45d27f5dd5f16e0c18c640de941c6ed

EDIT: Shooting into the air causes the game to crash? Trying to narrow it down.

EDIT AGAIN: Shooting a block seems to trigger it now?

https://gist.github.com/EsotericRyoushi/220800d22f539c2d6450427428a8acbf

**Comment by ChrisLane** [comment] 2020-06-03 07:59
Duplicate of #1145

**Closed as completed by ChrisLane** 2020-06-03 07:59 UTC

**Comment by EsotericRyoushi** [comment] 2020-06-03 09:44
OH, okay. thanks. I looked more into that one, and it just isn't fixed in the RELEASE yet. So I'd have to build it myself to get the fixes I'm guessing?

**Comment by ChrisLane** [comment] 2020-06-03 16:02
I just published a new update with this fix https://github.com/FlansMods/FlansMod/releases
