### ISSUE TITLE
Rounds won't start

### ISSUE THREAD

**Issue by GitDepository** [FlansMods/FlansMod#1182] opened 2020-03-17 20:17 UTC
**Describe the bug**
Pressing my keybind to open the teams menu does nothing even after starting the round and when I press my keybind to open the scores menu it says that time has run out. 

**To Reproduce**
Steps to reproduce the behaviour:
1. Create a map with /teams addMap map Map
2. Create two flags and spawners and connect them using the Stick of Connecting
3. Set the flags' team and map
4. Create a round with /teams addRound map TDM swat spetsnaz 5 100
5. Start the round with /teams start
6. Press the teams menu keybind (G), doesn't show anything
7. Press the score menu keybind (H), says that the time has run out.

**Expected behaviour**
The round would start, teams menu would open.

**Screenshots**
![image](https://user-images.githubusercontent.com/58197484/76897722-7f8fed80-6851-11ea-8507-f8e4a54af2e7.png)

**Versions (please complete the following information)**
 - Forge: 14.23.5.2847
 - Flan's Mod: 5.6.0-beta.6

Installed content packs are Simple Parts and Modern Warfare

**Comment by GitDepository** [comment] 2020-03-17 20:27
Installed content packs are Simple Parts and Modern Warfare

**Comment by Matcha7** [comment] 2020-03-26 18:54
Game also crashes when I press h or g

**Comment by azeman** [comment] 2020-06-07 17:59
Hello, I don't know if this was fixed somehow, but the issue is still here. A friend of mine and I tried to set up a simple TDM match but it just won't start, exactly as OP said. Pressing on G does nothing while H says Time Ran Out.

We're using latest version (5.6.0 beta 8).

**Comment by 4luk4s** [comment] 2020-08-09 14:54
Yeah. I believe they will fix this in the future, because i want to create Flan's teams server with rankeds. It doesn't work on 1.8 too.

**Comment by SeamusMullan** [comment] 2020-08-17 18:11
Is there any update on this fix, i just started having the same thing happen to me.

**Comment by jamioflan** [comment] 2021-01-29 14:14
Closed in favour of #1354

**Closed as completed by jamioflan** 2021-01-29 14:14 UTC
Labels: bug
