### ISSUE TITLE
Feature Request: Item names when hovering over items in various GUI.

### ISSUE THREAD

**Issue by ChatFawkes** [FlansMods/FlansMod#644] opened 2015-02-19 21:20 UTC
Hello, first of all thanks for the really fun mod.

I was wondering if you guys could possibly implement some type of hover tooltip, so that it's easier to know what items are needed in a crafting recipe for various content added. That way you can look up a recipe for a gun (or anything else for that matter) in the crafting table and then hover over the item required to see what they are named, so you can easily search for them in NEI. Currently I have to search NEI for an item with the matching texture to figure out what I need. This would be really great for new players who don't know what items are needed for various recipes. If it's too hard to implement then please feel free to close this issue.

**Comment by ChrisLane** [comment] 2015-04-11 23:55
Duplicate of #245.

**Closed by ChrisLane** 2015-04-11 23:55 UTC
Labels: Duplicate
