### ISSUE TITLE
Can't craft item: Metal Tail

### ISSUE THREAD

**Issue by Rangerrenze** [FlansMods/FlansMod#1244] opened 2020-06-15 17:37 UTC
Hello

I can't currently craft the Metal Tail from the simple parts pack, the given crafting recipe doesn't work, and the one that JEI gives is the same one as for the metal trapdoor so of course doesn't work as well

**Screenshots**
https://cdn.discordapp.com/attachments/721819690036494449/722140360679096371/unknown.png
https://cdn.discordapp.com/attachments/721819690036494449/722140508599615488/unknown.png
https://cdn.discordapp.com/attachments/721819690036494449/722140569211502642/unknown.png
https://cdn.discordapp.com/attachments/721819690036494449/722140646940606484/unknown.png

 - Forge: 1.12.2-14.23.5.2854
 - Flan's Mod: 1.12.2 -5.5.2
 mods:
Coroutil
CustomNPC
Flans
HWYLA
ICBM Classic
Journeymap
Simpleminingdrills
Weather

Flans extensions:
Apocolypse content
Mecha parts
Modern Warfare
Nerf Content
Simple Parts
Titan Content
WW2 Content
Ye Olde content
Zombie content

Thanks in advance

**Comment by ChrisLane** [comment] 2020-06-15 18:13
Duplicate of #945

**Closed as completed by ChrisLane** 2020-06-15 18:13 UTC
Labels: bug
