### ISSUE TITLE
Mod is cancelled forever?

### ISSUE THREAD

**Issue by mgdgfbhevdyeh** [FlansMods/FlansMod#826] opened 2016-08-21 10:15 UTC
![uc 20160821181345](https://cloud.githubusercontent.com/assets/20567492/17836615/1f2724e8-67cb-11e6-9d8e-060beb9a4a13.png)

**Comment by mgdgfbhevdyeh** [comment] 2016-08-21 10:15
is cancelled forever

**Comment by MarcinWieczorek** [comment] 2016-08-21 10:25
We are working on a port to the newest version of Minecraft. There is some progress but it has slowed down recently. The mod might be dead, but open source license will always give it a chance to reborn like phoenix from the ashes!

**Comment by mgdgfbhevdyeh** [comment] 2016-08-21 10:46
So,flans mod is dead?

**Comment by MarcinWieczorek** [comment] 2016-08-21 10:47
Possibly

**Comment by mgdgfbhevdyeh** [comment] 2016-08-21 11:44
if possible,the next update is 1.10.2?
（my english is no good）

**Comment by MarcinWieczorek** [comment] 2016-08-21 11:46
You can contribute to this fork:
https://github.com/gitgud-software/FlansMod

**Comment by PrototypeTheta** [comment] 2016-08-23 11:33
The mod is not cancelled. 

I have spent the last 6-7 months working on new features for it. The title of that video was a joke that should have become obvious upon watching the video.

**Comment by PrototypeTheta** [comment] 2016-08-23 11:35
Once said features are implemented I will think about porting to the newer version. If you've already made some headway with that I would be glad to hear about it.

**Comment by MarcinWieczorek** [comment] 2016-08-23 11:36
I and gitgud spent quite a lot of time updating the mod to new Minecraft. Only rendering is left and it seems impossible to get it done. Also I don't know much about new rendering API. I'm stuck.

**Comment by PrototypeTheta** [comment] 2016-08-23 11:39
Ouch, I had a go at updating to 1.9 a while back and got stuck there myself. Can't find any useful information about said API but I haven't exactly tried that hard. I'd rather focus on getting everything working on the current version for now, then port it in one go.

**Comment by MarcinWieczorek** [comment] 2016-08-23 11:40
I guess we're expecting our fork to be merged to master?

**Comment by PrototypeTheta** [comment] 2016-08-23 11:42
Could be tricky. You won't have access to most of the stuff I've been doing and that might complicate things..

**Comment by MarcinWieczorek** [comment] 2016-08-23 11:43
You mean push access or git conflicts?

**Comment by PrototypeTheta** [comment] 2016-08-23 11:51
Conflicts in the code itself as you'll have been updating an outdated version.

**Comment by MarcinWieczorek** [comment] 2016-08-23 11:53
I don't mind not having access to the main repository.

**Comment by PrototypeTheta** [comment] 2016-08-23 12:23
Well for GitHub perms I can't do anything. I don't have access either.

**Comment by MarcinWieczorek** [comment] 2016-08-23 12:30
I don't care. What's the problem?

**Comment by PrototypeTheta** [comment] 2016-08-23 12:38
The problem is we could end up with multiple different forks all doing different things. Ideally the 1.8 version would be completely finished before it is ported. But if you've already make headway we could end up just bolting those changes onto your version. Which may not even be a problem, just could get a little messy.

**Comment by MarcinWieczorek** [comment] 2016-08-23 12:40
I don't have much experience with working on multiple forks, but I'm aware it's gonna get messy as hell. I've put hours of work to that update and I'd appreciate it merged. I would help obviously.

**Comment by PrototypeTheta** [comment] 2016-08-23 12:49
If you've already got it working there's no need to do it twice.

I'm already maintaining a 1.7.10 version of the mod as it is so I'm having to port all this between versions already. Doing one more couldn't hurt right?

**Comment by MarcinWieczorek** [comment] 2016-08-23 12:50
We'll sort it out.  wtorek, 23 sierpnia 2016, 02:49PM +02:00 od PrototypeTheta  notifications@github.com :

**Comment by PrototypeTheta** [comment] 2016-08-23 12:54
Alright, let me know when you're ready to start accepting new features. If you need to get a hold of me I am normally active here:

http://minecraft-smp.de/index.php

**Comment by MarcinWieczorek** [comment] 2016-08-23 13:00
Ok, we can discuss this outside github. 
Send me an email or an im on XMPP  wtorek, 23 sierpnia 2016, 02:54PM +02:00 od PrototypeTheta  notifications@github.com :

**Comment by TypicalDarkness** [comment] 2016-08-25 14:37
Hi. I am also currently working on updating the mod. I sent you an email with more details.

**Comment by gitgud-software** [comment] 2016-09-05 16:20
Heya, a bit late to the conversation but I'll be frank and say PrototypeTheta may have a point, we may have things out of order trying to jump directly to 1.10.2 instead of incremental updates. I'm going to try and first see if we can make the jump from 1.8 to 1.8.9, and see how things go from there.

**Comment by MarcinWieczorek** [comment] 2016-09-06 15:37
@TypicalDarkness said he managed to run the mod, but he never replied to my email.

**Comment by Fexcraft** [comment] 2016-09-09 17:07
Uhm.. so well.. a while ago I updated an private copy of the mod to 1.10.2

I know how to update most things to 1.10.2 and it seems to work fine.
Except gun rendering (some classes are missing), and a few smaller bugs.
_(I sincerly don't care about guns currently anyways, I just like vehicles)_
*also vehicle guns do work.
 
So if there would be some official 1.10+ branch I'll help probably (after I figure out how github works ... >.>)
 
_Edit: No, I can't send you the mod to test it cause it will crash cause it's bound to other of my mods._

**Comment by gitgud-software** [comment] 2016-09-09 19:00
@Fexcraft We've been working on the fork at https://github.com/gitgud-software/FlansMod on the 1.10.2 thing if you want to check it out. I don't know if you're going to get an "official" branch unless we manage a complete port; right now @PrototypeTheta seems to want to work out the problems in the 1.8.9 version.

I don't honestly mind a dependency if it means the mod works though, but you may want to spin the relevant code into an API/library like some of the other projects do. At least post the repository or merge some of the stuff into ours? What can be done would be greatly appreciated.

**Comment by Fexcraft** [comment] 2016-09-10 08:24
@gitgud-software is that 'fork' working? (launching). Also the gun render quite much died in 1.8.9 as far I remember.

If it's about dependency... a part of the code is put into one of my mods, another into a _(private)_ server mod _(packethandler, cause the default one didn't work for some weird reason on my server, while it did in eclipse)_.

**Comment by MarcinWieczorek** [comment] 2016-09-10 12:06
Our work doesn't work.

**Comment by mgdgfbhevdyeh** [comment] 2016-09-10 12:27
@MarcinWieczorek work doesn't work？

**Comment by MarcinWieczorek** [comment] 2016-09-10 12:28
fork* that was a missclick ;P

**Comment by Fexcraft** [comment] 2016-09-10 13:23
Mine did till I wrecked it, and reupdating now again :P

**Comment by gitgud-software** [comment] 2016-09-13 00:29
@Fexcraft Hey, make sure to open up Issues so we can track what is and isn't working from your repo. It'd also be solid if you wrapped up some of the fexcraft imports into a library mod if possible. Right now the setup doesn't pull in the Fexcraft dependency/mappings either, so please update the build process when you get the chance.

**Comment by Fexcraft** [comment] 2016-09-13 08:40
@gitgud-software enabled the Issues thing.
About the fexcraft imports, I prepared a .jar file, I forgot though how to do the import/deendency stuff in eclipse (I'll put it into the /run/mods folder).
Or alternatively I could add all the classes to the src (after I add a signature and comments), if that would be better?

**Comment by TypicalDarkness** [comment] 2016-09-20 16:23
Hey, I'm still working on the project. I was gone for over a month because I didn't have a lot of time.

I removed big parts of the mod and started to from almost zero and then re-added the things I needed bit-by-bit. The rendering system I made uses .obj files and so far I have converted the gun models.
I also switched to .json instead of .txt for typeFiles.

https://github.com/TypicalDarkness/FlansMod

**Comment by Fexcraft** [comment] 2016-09-20 16:35
Ye, I thought also that json would simplify some stuff...

**Comment by TypicalDarkness** [comment] 2016-09-20 16:43
I wrote some code to convert txt -> json and so far I have converted bullets, guns and parts

**Comment by Fexcraft** [comment] 2016-09-20 16:58
@TypicalDarkness  When I downloaded the code from your fork to try it,
the "FlansUtils" class seems to be missing?

**Comment by TypicalDarkness** [comment] 2016-09-20 17:03
Sorry I seemed to have unticked the file when I comitted in Github desktop for some reason. Should work now

**Comment by Minecraft-SMP** [comment] 2016-09-21 16:17
Your rendering system uses only obj?

**Comment by TypicalDarkness** [comment] 2016-09-21 16:22
Yes. I could add support other formats though

**Comment by Minecraft-SMP** [comment] 2016-09-21 16:24
The mod live from the community, and all packages are using java models. not one is using obj till now.

**Comment by TypicalDarkness** [comment] 2016-09-21 16:25
I wrote a code to convert ModelRenderTurbo to .obj. I already converted most of the gun files

**Comment by Minecraft-SMP** [comment] 2016-09-21 16:26
then you have to publish the converter too. Most modelers have their own files and don't share.

**Comment by TypicalDarkness** [comment] 2016-09-21 16:29
Yep, I can do that.

**Comment by PrototypeTheta** [comment] 2016-09-21 16:36
I might just know someone who is up to the job of updating TMT. Can't say when it'll happen but I do feel preserving it should be a priority, as well as the current system to read configs from .txt files. As Manus pointed out, the mod survives on the community, so it is best to keep things as straightforward for them as possible. When we change things people tend to throw poo at me.

But any ways, I'm sure you know that I have been working on enhancing the current versions. Most
of this new content has been made available here (even if I haven't got control of this either)

https://github.com/Demitto/Flan-s-Mod-Plus/tree/master/src/main

Now most of the changes should be straightforward to port provided the mods general structure remains the same. Though do bear in mind that some of this will not be making its way into any official versions (map writer based content will be left out, but stuff like handling improvements, new effects and the new vehicles collision systems will be ported).

I should be returning to the UK in a few weeks time so I'll be around more to help with this.

**Comment by TypicalDarkness** [comment] 2016-09-21 16:52
The rendering is deprecated and Forge will remove support for it even more in the future. Storing models as actual files instead of classes has many advantages, for example that resource packs can change them.

We can have support for txt and json at the same time or we provide easy to use tools to convert the packs. If the content pack creators don't want to do it, I can do it for them.

**Comment by PrototypeTheta** [comment] 2016-09-21 17:11
I believe Flan hit a similar problem converting to 1.8. I didn't really understand back them but I remember him working on a system so that content creators would not have to deal with .jsons to get their models working.

**Comment by TypicalDarkness** [comment] 2016-09-21 17:29
Do you mean the vanilla json models for items that were introduced in 1.8? Yes it's really annoying that we now need to add extra files even when just adding a simple item. Mojang seems to remove more and more things from the game to external resources (maybe to make the game more modular or easier to modify)
But I was more talking about the json support that I added for typefiles.

**Comment by PrototypeTheta** [comment] 2016-09-21 17:40
Ah, I was under the impression that it would be difficult to preserve reading everything from txt. But if it's just something additional you've added then there literally isn't a problem.

As for the rendering stuff. Well, I do feel like cocking around with OpenGL.

**Comment by TypicalDarkness** [comment] 2016-09-21 17:49
Ok, but I still think using external files and the rendering forge suggests us to use would make the mod more future proof and maintainable.

**Comment by PrototypeTheta** [comment] 2016-09-21 18:18
Fair point. It's enough of a white elephant already.

**Comment by TypicalDarkness** [comment] 2016-09-21 18:33
Maybe this is slightly off-topic, but what I'm also dreaming of is having something like a "FlansCreator" in the future, a program that allows people to easily manage their content-pack withough having do deal with all the different files.

**Comment by PrototypeTheta** [comment] 2016-09-21 22:04
Well Toolbox is the closest we have to that in regards to it's abilities to generate the configs to go along with the models. Though I think with some proper up-to-date documentation messing around with the different files would hardly be a chore. But admittedly my PoV is perhaps skewed, having started on the old 1.2.5 system.

But hell, I must say I like the idea, it could potentially help with standardisation.

**Comment by PrototypeTheta** [comment] 2016-09-21 22:50
Ah. Just noticed something. Do any of the vehicles work when converted to .obj? Because I know model parts like tank barrels rely on the structure of TurboModelThingy parts, which may throw a spanner in the works with regards to converting everything to .obj.

**Comment by Fexcraft** [comment] 2016-09-22 09:06
_In the meantime there is me not understanding why some people talk about TMT as if it would be irriparably broken.._

http://prntscr.com/cky3sn that's about vehicles.
Turrent, Gun and wheels move just fine.

Only "broken" vehicle model found: https://github.com/Fexcraft/FlansMod/issues/4
(didn't check all yet though)

<s>If it's about deprecated methods, http://prntscr.com/cky5s3
in theory it would be possible to get vehicles with current rendering till 1.11;</s>
Nvm, this resulted to be easy fixable... now just gotta get rid of a white cube inside the vehicles.
http://prntscr.com/cky9sm http://prntscr.com/ckya5a

_Or is there something I understood completly wrong... ? .-._

**Comment by TypicalDarkness** [comment] 2016-09-22 15:11
The vehicles seem to work fine. I was talking about item/gun rendering. Sadly Forge decided to remove IItemRenderer and other useful classes for some reason and kind of force us to use their system...

**Comment by PrototypeTheta** [comment] 2016-09-22 16:37
Ah. I see. If it is just for guns then using .obj is no problem at all as the structuring is slightly different. It may potentially complicate my efforts to implement muzzle flash but it's nothing that can't be sorted out.

Sure, we'll have to lose that fancy effect where the vehicle model renders in your hand, but it's a feature I think we can live without.

**Comment by TypicalDarkness** [comment] 2016-09-22 18:45
I think fixing the old rendering IS possible but we would have to use a lot of hacky stuff. This is what I just did using @Fexcraft 's repo:
http://i.imgur.com/F07TZrl.png

We have to change the vanilla jsons to something like this to prevent normal rendering and then render the gun using GL:

`{
  "parent": "builtin/generated",
  "textures": {
    "layer0": "flansmod:items/RPD"
  },
  "display": {
    "thirdperson_righthand": {
      "scale": [ 0, 0, 0 ]
    },
    "thirdperson_lefthand": {
      "scale": [ 0, 0, 0 ]
    },
    "firstperson_lefthand": {
      "scale": [ 0, 0, 0 ]
    },
    "firstperson_righthand": {
      "scale": [ 0, 0, 0 ]
    }
  }
}`

Maybe there is another way to prevent the vanilla rendering, but I think Forge removed or plans to remove all other possibilities (apart from first person rendering maybe). Another problem is, that I haven't found out how we can render the ItemEntities (items on the ground) ourselves.

Note, that this is not the way forge wants us to do things and that we might run into some problems in the future but it would be relativeley easy to fix rendering for now and we wouldn't have to change anything in the contentpacks beside the vanilla .json files. (Also it would be easier to render vehicles in the players hand) 
I could still add support for .obj so we would have both systems.

Btw, I made a fix for the arm rotations on my repo which I could implement aswell.

**Comment by TypicalDarkness** [comment] 2016-09-22 20:07
@Fexcraft The white boxes are fixed if you move ClientProx::registerRenderers() to pre-init. (at least I haven't seen the boxes so far)

**Comment by PrototypeTheta** [comment] 2016-09-22 20:57
Technically speaking TurboModelThingy can already load .obj models. It's just a really rubbish way to do it. If you can add a way to do it properly on top of what is already there then go for it, more options is always more better.

**Comment by Fexcraft** [comment] 2016-09-22 21:33
@TypicalDarkness true, I forgot in the comment of the deprecated method was written it should go to preinit.

About about "hacky" and "not how forge wants it",
as I saw, and thinking about it currently...
The mod already had wrong name registry and other small things which aren't fml/forge norms as far I remember.
And hacky stuff isn't bad as long it it doesn't cause laggs/crashes/curruption and also doesn't cause incompabilities with other mods.
_#ownOpinionWhichMightChange_


Regarding Json:
If json files would be used to store all the data of vehicles/guns/whatever,
another advantage (which I didn't saw mentioned?) is that it would be easly possible to auto-complete missing data from a file and save it "fixed". (that's what I commonly do with my mod-files)

**Comment by TypicalDarkness** [comment] 2016-09-23 18:11
Now that there is dual-wielding in minecraft, I think it would be better to remove the off-hand feature and just allow certain guns to be dual-wielded. What do you think?

**Comment by mgdgfbhevdyeh** [comment] 2016-09-24 02:23
@TypicalDarkness 
 remove the off-hand.

**Comment by PrototypeTheta** [comment] 2016-09-24 07:31
I agree with you on duel wielding. Now that there is a proper system we may as well use it.

**Comment by GolddolphinSKB-Fexcraftian** [comment] 2016-09-27 19:58
Hey Guys, You probably know me from before.
{I'm the guy who made a retarded python program that never really worked properly, and was never really released well....eh}

The progress seems to be good here,

Anyway, I am here to pledge my support in a 1.10.2 modelling program manager thingy do da, ofc written in....

# Python

Anyway.... ehm, whoever is making the new systems, i would like to speak to nearer the time its slightly more completed, maybe[lel]

Anyway, progress report from the program is:

- render code sorta done...
- array's are mostly setup
- functions: newBox()

To do:

Reading .java and .obj stuff (Heard someone already done .obj so maybe sooner than you think)
Exporting to .java and .obj (probably gonna take a while....)
make a gui
user controls
shapebox maker
other stuff i forgotten...


This will probably be uploaded to github, so if you wish to help, please do.

This is the support i pledge for 1.10 flans, as java aint my thing.

Thank You.

**Comment by MarcinWieczorek** [comment] 2016-09-27 20:01
Gimme dem sourcez of your program, I need to study it!

**Comment by GolddolphinSKB-Fexcraftian** [comment] 2016-09-27 20:03
Ehm, its rather.... Well in infancy much.

It doesnt do anything at the moment.

**Comment by GolddolphinSKB-Fexcraftian** [comment] 2016-09-27 20:17
@MarcinWieczorek 

It has been published.
[](https://github.com/GolddolphinSKB-Fexcraftian/Flansmod-Modelling-Python)

I shall update it regularly.

**Comment by MarcinWieczorek** [comment] 2016-09-27 20:30
OK. I don't know anything about puthon and I've got no idea what to do with it. Maybe some other time.

**Comment by GolddolphinSKB-Fexcraftian** [comment] 2016-09-27 20:35
Its hilariously broken...

**Comment by TypicalDarkness** [comment] 2016-09-28 22:05
python <3
I could work on the obj stuff when we added proper support for it

**Comment by TypicalDarkness** [comment] 2016-10-04 16:21
Another question about dual wielding:
When should it be possible to shoot the gun in the offHand?

- Only when there is only a gun in the mainHand aswell? (kind of like vanilla, where the offHand is not really that important)
- Only when there is a gun in the mainHand or the mainHand is empty (prevent vanilla clicking in that case)?
- Always no mather what is held in the other hand? (prevent vanilla clicking)
- {Something else}

**Comment by MarcinWieczorek** [comment] 2016-10-04 16:54
Imho only pistols should allowed to be shot with ond hand. I would not let players shoot heavier guns with one hand if it would be not possible in real life. Multiplayer servers with Flan's mod are pretty cool and people usually know a lot about the mod. Then I would suggest a big recoil in that case

**Comment by TypicalDarkness** [comment] 2016-10-04 17:05
Yes, but my question was about when it should be possible to use the offHand gun (pistol) and override the vanilla action breaking blocks/attacking (left-clicking).

**Comment by mgdgfbhevdyeh** [comment] 2016-10-05 00:47
@MarcinWieczorek But Minecraft is very unscientific

**Comment by mgdgfbhevdyeh** [comment] 2016-12-13 06:11
#826 closed

**Comment by mgdgfbhevdyeh** [comment] 2016-12-13 06:12
#826 close

**Comment by Fexcraft** [comment] 2016-12-13 09:05
Unknown, theoretically you can just take the code from the repo/fork and compile it,
and get a "experimental - use on own responsability" version of the mod.

**Closed** 2016-12-30 16:41 UTC

**Comment by Apollon007** [comment] 2017-09-24 16:00
Is the project dead or not? ;(
