### ISSUE TITLE
Survivor mob not hostile

### ISSUE THREAD

**Issue by Larkenus** [FlansMods/FlansMod#947] opened 2018-08-28 22:25 UTC
I am playing in 1.12.2 version with the Apocalypse content pack. I spawn in to the apocalypse world and when I encounter the survivor mob, they act like a passive mob. I have tried removing mods, changing difficulty, and restarting the game to no avail. The survivor mob just won't attack me.

**Comment by ChrisLane** [comment] 2019-04-27 10:46
Duplicate of #912

**Closed as completed by ChrisLane** 2019-04-27 10:46 UTC
Labels: duplicate
