### ISSUE TITLE
Unable to place vehicles in SMP

### ISSUE THREAD

**Issue by Simpyo** [FlansMods/FlansMod#1025] opened 2019-03-22 14:22 UTC
As the title suggests, everyone on the server is unable to place vehicles. Nothing crashes but in the server console I get this message when someone attempts it:

 22.03 14:35:58 [Server] Server thread/FATAL [minecraft/MinecraftServer]: Error executing task
22.03 14:35:58 [Server] INFO java.util.concurrent.ExecutionException: java.lang.NoClassDefFoundError: net/minecraft/client/Minecraft
22.03 14:35:58 [Server] INFO at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_201]
22.03 14:35:58 [Server] INFO at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_201]
22.03 14:35:58 [Server] INFO at net.minecraft.util.Util.func_181617_a(SourceFile:47) [h.class:?]
22.03 14:35:58 [Server] INFO at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:723) [MinecraftServer.class:?]
22.03 14:35:58 [Server] INFO at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397) [nz.class:?]
22.03 14:35:58 [Server] INFO at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) [MinecraftServer.class:?]
22.03 14:35:58 [Server] INFO at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
22.03 14:35:58 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_201]
22.03 14:35:58 [Server] INFO Caused by: java.lang.NoClassDefFoundError: net/minecraft/client/Minecraft
22.03 14:35:58 [Server] INFO at com.flansmod.common.driveables.EntitySeat.<init>(EntitySeat.java:95) ~[EntitySeat.class:?]
22.03 14:35:58 [Server] INFO at com.flansmod.common.driveables.EntitySeat.<init>(EntitySeat.java:115) ~[EntitySeat.class:?]
22.03 14:35:58 [Server] INFO at com.flansmod.common.driveables.EntityDriveable.initType(EntityDriveable.java:185) ~[EntityDriveable.class:?]
22.03 14:35:58 [Server] INFO at com.flansmod.common.driveables.EntityPlane.initType(EntityPlane.java:88) ~[EntityPlane.class:?]
22.03 14:35:58 [Server] INFO at com.flansmod.common.driveables.EntityPlane.<init>(EntityPlane.java:74) ~[EntityPlane.class:?]
22.03 14:35:58 [Server] INFO at com.flansmod.common.driveables.EntityPlane.<init>(EntityPlane.java:80) ~[EntityPlane.class:?]
22.03 14:35:58 [Server] INFO at com.flansmod.common.driveables.ItemPlane.func_77659_a(ItemPlane.java:140) ~[ItemPlane.class:?]
22.03 14:35:58 [Server] INFO at net.minecraft.item.ItemStack.func_77957_a(ItemStack.java:217) ~[aip.class:?]
22.03 14:35:58 [Server] INFO at net.minecraft.server.management.PlayerInteractionManager.func_187250_a(PlayerInteractionManager.java:358) ~[or.class:?]
22.03 14:35:58 [Server] INFO at net.minecraft.network.NetHandlerPlayServer.func_147346_a(NetHandlerPlayServer.java:765) ~[pa.class:?]
22.03 14:35:58 [Server] INFO at net.minecraft.network.play.client.CPacketPlayerTryUseItem.func_148833_a(SourceFile:32) ~[mb.class:?]
22.03 14:35:58 [Server] INFO at net.minecraft.network.play.client.CPacketPlayerTryUseItem.func_148833_a(SourceFile:9) ~[mb.class:?]
22.03 14:35:58 [Server] INFO at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) ~[hv$1.class:?]
22.03 14:35:58 [Server] INFO at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_201]
22.03 14:35:58 [Server] INFO at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_201]
22.03 14:35:58 [Server] INFO at net.minecraft.util.Util.func_181617_a(SourceFile:46) ~[h.class:?]
22.03 14:35:58 [Server] INFO ... 5 more 

Everything works fine in Singleplayer, I can place down every vehicle, it's just in Multiplayer that nothing happens.

**Screenshots**

**Versions (please complete the following information):**
 - Forge: 1.12.2 14.23.5.2814
 - Flan's Mod: 5.6 Beta4

Not entirely sure whether this is a mod issue or something to do with my server, but I thought I'd post here just in case

**Comment by ChrisLane** [comment] 2019-03-22 17:10
Duplicate of #1017

**Closed as completed by ChrisLane** 2019-03-22 17:10 UTC
Labels: bug
