### ISSUE TITLE
Bomb Bay Uncraftable.

### ISSUE THREAD

**Issue by WaltWhitmanOG** [FlansMods/FlansMod#1208] opened 2020-05-05 07:36 UTC
I cannot craft the bomb bay. I have tried every recipe imaginable, and when I click it in JEI, it doesn't give me options to craft it. 

**Describe the bug**

**To Reproduce**
Steps to reproduce the behaviour:
1. 
2. 
3. 
4. 

**Expected behaviour**

**Screenshots**

**Versions (please complete the following information)**
 - Forge: 14.23.5.2847
 - Flan's Mod: 5.5.2

**Additional context**

**Comment by ChrisLane** [comment] 2020-05-05 08:10
A quick search of existing issues would find the solution to your problem.
Duplicate of #1170

**Closed as completed by ChrisLane** 2020-05-05 08:10 UTC
Labels: bug
