### ISSUE TITLE
Incompatibility between Flan and Malisis' Core/Doors

### ISSUE THREAD

**Issue by Mortivarus** [FlansMods/FlansMod#1217] opened 2020-05-09 20:37 UTC
**Describe the bug**
When attempting to fire any of the tanks, the shell either explodes in the players face or it doesn't fire at all. 

**To Reproduce**
Steps to reproduce the behaviour:
1. Enter any of the tanks
2. Load a tank shell and attempt to fire.

**Expected behaviour**
Disabling of Malisis' Core and Doors causes correct behaviour in the form of the shot firing, hitting and destroying a target.

**Versions (please complete the following information)**
 - Forge: 14.23.5.2838
 - Flan's Mod: tested with 5.5.2 and up, including beta version 7  
 - Malisis Doors: 1.12.2-7.3.0
 - Malisis Core: 1.12.2.6.5.1

**Additional context**
Mod author of Malisis' Core/Doors has been informed of the issue. However as they are infrequently available and their mod seemingly abandoned, it seems unlikely they're going to be much help.

Issue seems to be a duplicate of #1172, however this has been closed for an inexplicable reason without providing a solution.

**Comment by Mortivarus** [comment] 2020-05-09 20:47
Addendum: further testing with Flan's mod beta version 7 shows that at close range no shots are fired at all. At longer ranges it causes an entity tick crash. Issue seems to concern anything that shoots. 
[crash-2020-05-09_22.42.54-server.txt](https://github.com/FlansMods/FlansMod/files/4604455/crash-2020-05-09_22.42.54-server.txt)
.

**Comment by Liruxo** [comment] 2020-05-09 21:43
Link to the [issue](https://github.com/Ordinastie/MalisisDoors/issues/283) at MalisisDoors
Edited crashlog in a [gist](https://gist.github.com/Liruxo/58495c790e3468a06ce2b5ebca3bd57e) for better readability

**Comment by CaveMiner1215** [comment] 2020-05-10 00:25
This is also a duplicate of issue #1204.

**Comment by Mortivarus** [comment] 2020-05-10 00:55
Ah thanks, had not seen that pop up when I looked up 'malisis' in the issues list.

**Comment by ChrisLane** [comment] 2020-05-10 10:17
Closing this. Details in #1145

**Closed as completed by ChrisLane** 2020-05-10 10:17 UTC
Labels: bug

**Comment by Mortivarus** [comment] 2020-05-10 10:33
Any chance of it being fixable any time soon though? As the original issue has been around since last year, and is still present in all beta versions. I'm also curious how malisis then fucks it up, as it seems to work normally without it.

**Comment by ChrisLane** [comment] 2020-05-10 11:50
> Any chance of it being fixable any time soon though? As the original issue has been around since last year, and is still present in all beta versions. I'm also curious how malisis then fucks it up, as it seems to work normally without it.

https://github.com/FlansMods/FlansMod/issues/1145#issuecomment-626315900
