### ISSUE TITLE
Game crashes when crafting Armour

### ISSUE THREAD

**Issue by bunny246** [FlansMods/FlansMod#1131] opened 2019-09-18 22:19 UTC
**To Reproduce**
Steps to reproduce the crash:
1. Place a Armour/weapon crafting box
2. open it and press the arrow twice
3. then crashes

**Screenshots**
(https://user-images.githubusercontent.com/55502292/65189318-95f1f380-da3e-11e9-92f4-bf2c6c2c56f3.png)
(https://user-images.githubusercontent.com/55502292/65189406-d3568100-da3e-11e9-8e43-da5b7af1da55.png)

**Versions (please complete the following information)**
 - Forge: forge-1.12-14.21.1.2443
 - Flan's Mod: 5.5.1 for MC 1.12.2

**Crash Log**
(https://github.com/FlansMods/FlansMod/files/3628521/crash-2019-09-18_18.05.27-client.txt)

**Additional context**
probably crashes in creative but i put what i was doing in the steps

I was using vanilla fix so it didn't really crash but it still says its a crash
and to report this

**Comment by Liruxo** [comment] 2019-09-18 22:33
Version 5.5.1 is out of date and no longer supported. Please try using the latest FlansMod version, available here: https://github.com/FlansMods/FlansMod/releases

**Comment by ChrisLane** [comment] 2019-09-19 08:03
Duplicate of #854.
The issue was already fixed in d02694aa1fe6d254606e82bc2c9735221d05c56f, to get the fix you need to do what @Liruxo said.

**Closed as completed by ChrisLane** 2019-09-19 08:03 UTC
Labels: crash
