### ISSUE TITLE
Please help with this 1.12.2 crash when turning on 

### ISSUE THREAD

**Issue by UltiMultiGamer** [FlansMods/FlansMod#992] opened 2019-01-17 01:13 UTC
I have read the readme.txt and I have the correct forge version, but the game will not stop crashing. I put the content packs into the flan folder. Then, after launching, after initialization phase 2 everything breaks. Here is the crash logs. Please don't judge my mac. Please help and / or fix this bug.

---- Minecraft Crash Report ----

WARNING: coremods are present:
  MicdoodlePlugin (MicdoodleCore-1.12.2-4.0.1.181.jar)
  BetterFoliageLoader (BetterFoliage-MC1.12-2.2.0.jar)
  ForgelinPlugin (Forgelin-1.8.2 (1).jar)
Contact their authors BEFORE contacting forge

// On the bright side, I bought you a teddy bear!

Time: 1/16/19 6:13 PM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Flan's Mod: Apocalypse (flansmodapocalypse)
Caused by: java.lang.NullPointerException
	at com.flansmod.apocalypse.common.FlansModApocalypse.preInit(FlansModApocalypse.java:179)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:624)
	at sun.reflect.GeneratedMethodAccessor9.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:218)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:196)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:135)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:627)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:252)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:466)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:377)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Mac OS X (x86_64) version 10.13.6
	Java Version: 1.8.0_74, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 2990344800 bytes (2851 MB) / 3959422976 bytes (3776 MB) up to 5368709120 bytes (5120 MB)
	JVM Flags: 7 total; -Xmx5G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2768 Optifine OptiFine_1.12.2_HD_U_E3 56 mods loaded, 56 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID                  | Version           | Source                                              | Signature                                |
	|:----- |:------------------- |:----------------- |:--------------------------------------------------- |:---------------------------------------- |
	| UCH   | minecraft           | 1.12.2            | minecraft.jar                                       | None                                     |
	| UCH   | mcp                 | 9.42              | minecraft.jar                                       | None                                     |
	| UCH   | FML                 | 8.0.99.99         | forge-1.12.2-14.23.5.2768.jar                       | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCH   | forge               | 14.23.5.2768      | forge-1.12.2-14.23.5.2768.jar                       | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCH   | micdoodlecore       |                   | minecraft.jar                                       | None                                     |
	| UCH   | securitycraft       | v1.8.10           | [1.12.2]+SecurityCraft+v1.8.10.jar                  | None                                     |
	| UCH   | aoa3                | 3.0-SNAPSHOT-10   | aoa3-SNAPSHOT-10.jar                                | None                                     |
	| UCH   | baubles             | 1.5.2             | Baubles-1.12-1.5.2.jar                              | None                                     |
	| UCH   | forgelin            | 1.8.2             | Forgelin-1.8.2 (1).jar                              | None                                     |
	| UCH   | betterfoliage       | 2.2.0             | BetterFoliage-MC1.12-2.2.0.jar                      | None                                     |
	| UCH   | biomesoplenty       | 7.0.1.2422        | BiomesOPlenty-1.12.2-7.0.1.2422-universal.jar       | None                                     |
	| UCH   | codechickenlib      | 3.2.2.353         | CodeChickenLib-1.12.2-3.2.2.353-universal.jar       | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| UCH   | redstoneflux        | 2.1.0             | RedstoneFlux-1.12-2.1.0.6-universal (1).jar         | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| UCH   | brandonscore        | 2.4.9             | BrandonsCore-1.12.2-2.4.9.195-universal.jar         | None                                     |
	| UCH   | cofhcore            | 4.6.1             | CoFHCore-1.12.2-4.6.1.22-universal (2).jar          | None                                     |
	| UCH   | cofhworld           | 1.3.0             | CoFHWorld-1.12.2-1.3.0.6-universal (1).jar          | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| UCH   | mantle              | 1.12-1.3.3.39     | Mantle-1.12-1.3.3.39.jar                            | None                                     |
	| UCH   | jei                 | 4.13.1.225        | jei_1.12.2-4.13.1.225.jar                           | None                                     |
	| UCH   | twilightforest      | 3.8.689           | twilightforest-1.12.2-3.8.689-universal.jar         | None                                     |
	| UCH   | tconstruct          | 1.12.2-2.11.0.106 | TConstruct-1.12.2-2.11.0.106.jar                    | None                                     |
	| UCH   | conarm              | 1.2.0.2           | conarm-1.12.2-1.2.0.2.jar                           | 5d5b8aee896a4f5ea3f3114784742662a67ad32f |
	| UCH   | extendedrenderer    | v1.0              | coroutil-1.12.1-1.2.14.jar                          | None                                     |
	| UCH   | coroutil            | 1.12.1-1.2.14     | coroutil-1.12.1-1.2.14.jar                          | None                                     |
	| UCH   | configmod           | v1.0              | coroutil-1.12.1-1.2.14.jar                          | None                                     |
	| UCH   | thermalfoundation   | 2.6.1             | ThermalFoundation-1.12.2-2.6.1.22-universal (2).jar | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| UCH   | draconicevolution   | 2.3.18            | Draconic-Evolution-1.12.2-2.3.18.329-universal.jar  | None                                     |
	| UCH   | enhancedvisuals     | 1.0               | EnhancedVisuals_v1.2.1_mc1.12.2.jar                 | None                                     |
	| UCH   | galacticraftcore    | 4.0.1.181         | GalacticraftCore-1.12.2-4.0.1.181.jar               | None                                     |
	| UCH   | galacticraftplanets | 4.0.1.181         | Galacticraft-Planets-1.12.2-4.0.1.181.jar           | None                                     |
	| UCH   | mjrlegendslib       | 1.12.2-1.1.6      | MJRLegendsLib-1.12.2-1.1.6.jar                      | b02331787272ec3515ebe63ecdeea0d746653468 |
	| UCH   | extraplanets        | 1.12.2-0.4.5      | ExtraPlanets-1.12.2-0.4.5.jar                       | b02331787272ec3515ebe63ecdeea0d746653468 |
	| UCH   | flansmod            | 5.5.1             | Flan's Mod-1.12.2-5.5.1.jar                         | None                                     |
	| UCEE  | flansmodapocalypse  | 1.0               | Flan's Mod-1.12.2-5.5.1.jar                         | None                                     |
	| UC    | forestry            | 5.8.1.322         | forestry_1.12.2-5.8.1.322.jar                       | None                                     |
	| UC    | waila               | 1.8.26            | Hwyla-1.8.26-B41_1.12.2.jar                         | None                                     |
	| UC    | icbmclassic         | 1.12.2-3.0.0.29   | ICBM-classic-1.12.2-3.0.0b29.jar                    | None                                     |
	| UC    | journeymap          | 1.12.2-5.5.3      | journeymap-1.12.2-5.5.3.jar                         | None                                     |
	| UC    | levelup2            | ${version}        | Level+Up!+2-1.1.22-1.12.jar                         | None                                     |
	| UC    | megaloot            | 0.2.30            | megaloot-1.12.2-0.2.30.jar                          | None                                     |
	| UC    | mts                 | 12.3.0            | Minecraft+Transport+Simulator-1.12.2-12.3.0.jar     | None                                     |
	| UC    | mtsofficialpack     | 8.0.0             | MTS_Official_Pack_V08.jar                           | None                                     |
	| UC    | thermalexpansion    | 5.5.2             | ThermalExpansion-1.12.2-5.5.2.39-universal (1).jar  | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| UC    | omlib               | 3.0.1-162         | omlib-1.12.2-3.0.1-162.jar                          | None                                     |
	| UC    | openmodularturrets  | 3.0.1-264         | openmodularturrets-1.12.2-3.0.1-264.jar             | None                                     |
	| UC    | harvestcraft        | 1.12.2z           | Pam's+HarvestCraft+1.12.2za.jar                     | None                                     |
	| UC    | placebo             | 1.5.0             | Placebo-1.12.2-1.5.0.jar                            | None                                     |
	| UC    | ptrmodellib         | 1.0.3             | PTRLib-1.0.3.jar                                    | None                                     |
	| UC    | silentlib           | 3.0.9             | SilentLib-1.12.2-3.0.9-159.jar                      | None                                     |
	| UC    | silentgems          | 2.8.10            | SilentsGems-1.12.2-2.8.10-308.jar                   | None                                     |
	| UC    | sgextraparts        | 1.4.5             | SGExtraParts-1.12.2-1.4.5-43.jar                    | None                                     |
	| UC    | silentgemstic       | 0.1.1             | SilentsGems-TiC-1.12.2-0.1.1-5.jar                  | None                                     |
	| UC    | sonarcore           | 5.0.19            | sonarcore-1.12.2-5.0.19-20.jar                      | None                                     |
	| UC    | thermaldynamics     | 2.5.3             | ThermalDynamics-1.12.2-2.5.3.16-universal.jar       | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| UC    | wanionlib           | 1.12.2-1.5        | WanionLib-1.12.2-1.5.jar                            | None                                     |
	| UC    | worleycaves         | 1.3.0             | worleycaves-1.3.0.jar                               | None                                     |
	| UC    | unidict             | 1.12.2-2.9.1      | UniDict-1.12.2-2.9.1 (1).jar                        | None                                     |

	Loaded coremods (and transformers): 
MicdoodlePlugin (MicdoodleCore-1.12.2-4.0.1.181.jar)
  micdoodle8.mods.miccore.MicdoodleTransformer
BetterFoliageLoader (BetterFoliage-MC1.12-2.2.0.jar)
  mods.betterfoliage.loader.BetterFoliageTransformer
ForgelinPlugin (Forgelin-1.8.2 (1).jar)
  
	GL info: ' Vendor: 'Intel Inc.' Version: '2.1 INTEL-10.36.19' Renderer: 'Intel Iris OpenGL Engine'
	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerHarvestTools (Enabled/Forced)
		- TinkerMeleeWeapons (Enabled/Forced)
		- TinkerRangedWeapons (Enabled/Forced)
		- TinkerModifiers (Enabled/Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- TinkerModelRegister (Enabled/Forced)
		- wailaIntegration (Enabled/Not Forced)

	OptiFine Version: OptiFine_1.12.2_HD_U_E3
	OptiFine Build: 20181210-121000
	Render Distance Chunks: 12
	Mipmaps: 3
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 2.1 INTEL-10.36.19
	OpenGlRenderer: Intel Iris OpenGL Engine
	OpenGlVendor: Intel Inc.
	CpuCount: 4

**Comment by DatBoiFedoy** [comment] 2019-01-17 01:14
There is something wrong with the "Flan's Mod Apocalypse", which is located in the  "Detailed walkthrough"

**Comment by ChrisLane** [comment] 2019-01-17 07:58
Thanks for the further information.
It looks like you're using an old version of the mod and I think this issue has already been fixed.

Please download the latest pre-release from here and let me know if you still encounter the crash:
https://github.com/FlansMods/FlansMod/releases

**Comment by ChrisLane** [comment] 2019-01-17 09:07
Duplicate of #964, #958, #925...
Please search existing tickets before creating a new one in future.

**Closed as completed by ChrisLane** 2019-01-17 09:07 UTC
Labels: crash
