### ISSUE TITLE
Why dose it crash?

### ISSUE THREAD

**Issue by WeareunitedMuricans** [FlansMods/FlansMod#1014] opened 2019-03-08 04:18 UTC
**To Reproduce**
Steps to reproduce the crash:
1. Make Sure you have Flans Mod Parts And Modern Warfare Pac
2. Pick Some Attackments Scope,Silencer Etc
3. Get Modification Table
4. Place It In World

**Screenshots**

**Versions (please complete the following information):**
 - Forge: 1.12.2
 - Flan's Mod: 1.12.2

**Additional context**
<!-- Add any other context about the problem here.

---- Minecraft Crash Report ----

WARNING: coremods are present:
  ObfuscatePlugin (obfuscate-0.2.6-1.12.2.jar)
  DynamicSurroundingsCore (DynamicSurroundings-1.12.2-3.4.7.2.jar)
Contact their authors BEFORE contacting forge

// Oops.

Time: 3/7/19 10:13 PM
Description: Updating screen events

java.lang.NullPointerException: Updating screen events
	at net.minecraft.inventory.Container.func_184996_a(Container.java:246)
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_187098_a(PlayerControllerMP.java:566)
	at net.minecraft.client.gui.inventory.GuiContainer.func_184098_a(GuiContainer.java:638)
	at net.minecraft.client.gui.inventory.GuiContainer.func_73864_a(GuiContainer.java:392)
	at com.flansmod.client.gui.GuiGunModTable.func_73864_a(GuiGunModTable.java:274)
	at net.minecraft.client.gui.GuiScreen.func_146274_d(GuiScreen.java:533)
	at com.flansmod.client.gui.GuiGunModTable.func_146274_d(GuiGunModTable.java:235)
	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:501)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1758)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1097)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:397)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at net.minecraft.inventory.Container.func_184996_a(Container.java:246)
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_187098_a(PlayerControllerMP.java:566)
	at net.minecraft.client.gui.inventory.GuiContainer.func_184098_a(GuiContainer.java:638)
	at net.minecraft.client.gui.inventory.GuiContainer.func_73864_a(GuiContainer.java:392)
	at com.flansmod.client.gui.GuiGunModTable.func_73864_a(GuiGunModTable.java:274)
	at net.minecraft.client.gui.GuiScreen.func_146274_d(GuiScreen.java:533)
	at com.flansmod.client.gui.GuiGunModTable.func_146274_d(GuiGunModTable.java:235)
	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:501)

-- Affected screen --
Details:
	Screen name: com.flansmod.client.gui.GuiGunModTable

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['TipsyBrandy'/15, l='MpServer', x=84.40, y=64.00, z=-510.01]]
	Chunk stats: MultiplayerChunkCache: 600, 600
	Level seed: 0
	Level generator: ID 01 - flat, ver 0. Features enabled: false
	Level generator options: 
	Level spawn location: World: (-1511,4,113), Chunk: (at 9,0,1 in -95,7; contains blocks -1520,0,112 to -1505,255,127), Region: (-3,0; contains chunks -96,0 to -65,31, blocks -1536,0,0 to -1025,255,511)
	Level time: 67125 game time, 67125 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Forced entities: 157 total; [EntityCamera['unknown'/1341458, l='MpServer', x=241.63, y=60.62, z=-378.75], EntityCreeper['Creeper'/2205754, l='MpServer', x=117.50, y=64.00, z=-558.50], EntityXPOrb['Experience Orb'/2178153, l='MpServer', x=145.50, y=64.00, z=-414.37], EntityXPOrb['Experience Orb'/2178155, l='MpServer', x=141.94, y=64.00, z=-417.22], EntityXPOrb['Experience Orb'/2178154, l='MpServer', x=142.53, y=64.00, z=-415.86], EntityWheel['entity.Wheel.name'/1441870, l='MpServer', x=205.86, y=64.00, z=-381.11], EntityWheel['entity.Wheel.name'/1441868, l='MpServer', x=209.14, y=64.00, z=-377.90], EntityWheel['entity.Wheel.name'/1441869, l='MpServer', x=208.02, y=64.00, z=-381.74], EntitySeat['entity.Seat.name'/1441866, l='MpServer', x=206.93, y=66.25, z=-378.82], EntityWheel['entity.Wheel.name'/1441867, l='MpServer', x=206.97, y=64.00, z=-377.27], EntityVehicle['M18 Hellcat'/1441864, l='MpServer', x=207.50, y=64.62, z=-379.50], EntitySeat['entity.Seat.name'/1441865, l='MpServer', x=206.93, y=65.62, z=-379.84], EntitySpider['Spider'/2205766, l='MpServer', x=46.50, y=64.00, z=-589.50], EntityXPOrb['Experience Orb'/2147415, l='MpServer', x=174.58, y=64.00, z=-447.68], EntityCamera['unknown'/1441903, l='MpServer', x=207.50, y=64.62, z=-379.50], EntityWheel['entity.Wheel.name'/2015388, l='MpServer', x=196.15, y=64.00, z=-389.39], EntitySpider['Spider'/2180259, l='MpServer', x=102.95, y=64.00, z=-527.95], EntityWheel['entity.Wheel.name'/2015386, l='MpServer', x=188.42, y=64.00, z=-390.95], EntityWheel['entity.Wheel.name'/2015387, l='MpServer', x=188.80, y=62.00, z=-387.50], EntityPlane['A10'/2015384, l='MpServer', x=191.44, y=64.00, z=-388.97], EntityItem['item.item.spiderEye'/2202791, l='MpServer', x=114.52, y=64.00, z=-482.80], EntitySeat['entity.Seat.name'/2015385, l='MpServer', x=197.66, y=67.20, z=-387.78], EntityItem['item.item.string'/2202790, l='MpServer', x=113.37, y=64.00, z=-483.58], EntityCamera['unknown'/2015423, l='MpServer', x=191.44, y=64.00, z=-388.97], EntityWheel['entity.Wheel.name'/1918125, l='MpServer', x=175.03, y=63.00, z=-389.52], EntityWheel['entity.Wheel.name'/1918124, l='MpServer', x=184.99, y=64.00, z=-383.17], EntitySeat['entity.Seat.name'/1918121, l='MpServer', x=186.96, y=65.04, z=-384.35], EntityPlane['EC665 "Tiger"'/1918120, l='MpServer', x=183.88, y=64.01, z=-385.50], EntityWheel['entity.Wheel.name'/1918123, l='MpServer', x=186.24, y=63.00, z=-385.72], EntitySeat['entity.Seat.name'/1918122, l='MpServer', x=185.62, y=65.62, z=-385.23], EntityWheel['entity.Wheel.name'/1709274, l='MpServer', x=174.91, y=64.00, z=-380.17], EntityWheel['entity.Wheel.name'/1709275, l='MpServer', x=174.91, y=64.00, z=-380.17], EntityVehicle['M45 .50Cal Quad Mount'/1709272, l='MpServer', x=176.50, y=64.63, z=-380.50], EntitySeat['entity.Seat.name'/1709273, l='MpServer', x=176.22, y=64.81, z=-380.22], EntityWheel['entity.Wheel.name'/1709276, l='MpServer', x=177.95, y=64.00, z=-379.66], EntityWheel['entity.Wheel.name'/1709277, l='MpServer', x=177.49, y=64.00, z=-381.86], EntityZombieVillager['Zombie Villager'/2197741, l='MpServer', x=52.50, y=64.00, z=-430.50], EntityCamera['unknown'/1918160, l='MpServer', x=183.88, y=64.01, z=-385.50], EntityCreeper['Creeper'/2197747, l='MpServer', x=54.50, y=64.00, z=-440.50], EntityXPOrb['Experience Orb'/2181373, l='MpServer', x=127.14, y=64.00, z=-424.58], EntityZombie['Zombie'/2204865, l='MpServer', x=29.17, y=64.00, z=-584.17], EntityZombie['Zombie'/2204864, l='MpServer', x=18.50, y=64.00, z=-575.50], EntityXPOrb['Experience Orb'/2127151, l='MpServer', x=153.66, y=64.00, z=-391.37], EntityXPOrb['Experience Orb'/2127152, l='MpServer', x=154.55, y=64.00, z=-391.82], EntityXPOrb['Experience Orb'/2127153, l='MpServer', x=154.08, y=64.00, z=-392.04], EntityCamera['unknown'/1709321, l='MpServer', x=176.50, y=64.63, z=-380.50], EntityItem['item.item.string'/2185478, l='MpServer', x=117.01, y=64.00, z=-448.91], EntitySpider['Spider'/2183443, l='MpServer', x=32.50, y=64.00, z=-454.50], EntityWitch['Witch'/2182517, l='MpServer', x=134.21, y=64.00, z=-499.69], EntityZombie['Zombie'/2194804, l='MpServer', x=127.72, y=64.00, z=-526.81], EntityZombieVillager['Zombie Villager'/2196860, l='MpServer', x=96.56, y=64.00, z=-546.76], EntityZombieVillager['Zombie Villager'/2196862, l='MpServer', x=98.68, y=64.00, z=-552.84], EntitySpider['Spider'/2177344, l='MpServer', x=79.84, y=64.00, z=-511.36], EntityItem['item.item.string'/2205099, l='MpServer', x=99.78, y=64.00, z=-499.44], EntityItem['item.item.spiderEye'/2205100, l='MpServer', x=99.50, y=64.00, z=-500.15], EntityVehicle['Bofors 40mm AA Gun'/1700233, l='MpServer', x=173.66, y=64.07, z=-375.47], EntityWheel['entity.Wheel.name'/1700235, l='MpServer', x=172.45, y=64.00, z=-376.49], EntitySeat['entity.Seat.name'/1700234, l='MpServer', x=173.36, y=64.21, z=-374.76], EntityWheel['entity.Wheel.name'/1700237, l='MpServer', x=174.38, y=63.00, z=-374.54], EntityWheel['entity.Wheel.name'/1700236, l='MpServer', x=172.14, y=64.00, z=-375.02], EntityWheel['entity.Wheel.name'/1700238, l='MpServer', x=174.69, y=63.00, z=-376.01], EntityCamera['unknown'/1700280, l='MpServer', x=173.66, y=64.07, z=-375.47], EntityStray['Stray'/2196872, l='MpServer', x=130.57, y=64.00, z=-542.42], EntityStray['Stray'/2196874, l='MpServer', x=140.50, y=64.00, z=-557.50], EntityCreeper['Creeper'/2196877, l='MpServer', x=126.80, y=64.00, z=-539.82], EntityCreeper['Creeper'/2196876, l='MpServer', x=134.60, y=64.00, z=-546.34], EntityStray['Stray'/2145680, l='MpServer', x=100.22, y=64.00, z=-453.34], EntityXPOrb['Experience Orb'/2148754, l='MpServer', x=169.99, y=63.00, z=-451.75], EntityXPOrb['Experience Orb'/2148755, l='MpServer', x=170.45, y=63.00, z=-450.61], EntityWheel['entity.Wheel.name'/1026491, l='MpServer', x=257.94, y=64.00, z=-361.97], EntityXPOrb['Experience Orb'/2148756, l='MpServer', x=169.02, y=63.00, z=-451.75], EntityWheel['entity.Wheel.name'/1026490, l='MpServer', x=256.45, y=64.00, z=-365.68], EntityPlane['F22 Raptor'/1026488, l='MpServer', x=259.92, y=64.62, z=-364.92], EntityXPOrb['Experience Orb'/2182625, l='MpServer', x=120.86, y=64.00, z=-408.27], EntityXPOrb['Experience Orb'/2182624, l='MpServer', x=123.04, y=64.00, z=-417.30], EntityCamera['unknown'/1445342, l='MpServer', x=203.50, y=60.63, z=-397.50], EntityXPOrb['Experience Orb'/2204143, l='MpServer', x=118.55, y=64.00, z=-477.07], EntityXPOrb['Experience Orb'/2204142, l='MpServer', x=118.40, y=64.00, z=-476.32], EntityWheel['entity.Wheel.name'/1445318, l='MpServer', x=202.12, y=60.00, z=-398.46], EntitySpider['Spider'/2200049, l='MpServer', x=152.79, y=64.00, z=-533.17], EntityWheel['entity.Wheel.name'/1445319, l='MpServer', x=202.68, y=60.00, z=-396.03], EntityXPOrb['Experience Orb'/2204144, l='MpServer', x=119.32, y=64.00, z=-475.44], EntitySeat['entity.Seat.name'/1445316, l='MpServer', x=203.34, y=61.75, z=-398.10], EntityWheel['entity.Wheel.name'/1445317, l='MpServer', x=204.32, y=60.00, z=-398.97], EntityVehicle['Cruiser MkVI Crusader'/1445315, l='MpServer', x=203.50, y=60.63, z=-397.50], EntitySpider['Spider'/2200052, l='MpServer', x=147.08, y=64.00, z=-529.12], EntityWheel['entity.Wheel.name'/1445320, l='MpServer', x=204.88, y=60.00, z=-396.53], EntityStray['Stray'/2200030, l='MpServer', x=152.50, y=64.00, z=-459.76], EntityWheel['entity.Wheel.name'/1506844, l='MpServer', x=197.35, y=64.00, z=-382.20], EntityWheel['entity.Wheel.name'/1506845, l='MpServer', x=197.56, y=64.00, z=-384.44], EntityWheel['entity.Wheel.name'/1506842, l='MpServer', x=193.79, y=62.44, z=-384.79], EntityCamera['unknown'/1026562, l='MpServer', x=259.92, y=64.62, z=-364.92], EntityWheel['entity.Wheel.name'/1506843, l='MpServer', x=193.58, y=63.00, z=-382.55], EntityVehicle['Chi-Ha'/1506840, l='MpServer', x=195.36, y=63.91, z=-383.51], EntitySeat['entity.Seat.name'/1506841, l='MpServer', x=195.37, y=64.83, z=-383.43], EntityZombie['Zombie'/2209341, l='MpServer', x=29.50, y=64.00, z=-563.50], EntityStray['Stray'/2201151, l='MpServer', x=81.54, y=64.00, z=-583.72], EntityCamera['unknown'/1506868, l='MpServer', x=195.37, y=63.89, z=-383.51], EntityXPOrb['Experience Orb'/2176515, l='MpServer', x=168.67, y=64.00, z=-432.39], EntityXPOrb['Experience Orb'/2176517, l='MpServer', x=166.02, y=64.00, z=-435.64], EntityXPOrb['Experience Orb'/2176516, l='MpServer', x=172.13, y=64.00, z=-435.82], EntityEnderman['Enderman'/2176525, l='MpServer', x=148.39, y=64.00, z=-509.49], EntityEnderman['Enderman'/2176526, l='MpServer', x=158.33, y=64.00, z=-507.39], EntityZombie['Zombie'/2176530, l='MpServer', x=156.50, y=64.00, z=-480.50], EntitySpider['Spider'/2185751, l='MpServer', x=162.03, y=64.00, z=-476.02], EntityXPOrb['Experience Orb'/2175517, l='MpServer', x=160.83, y=63.00, z=-431.25], EntityXPOrb['Experience Orb'/2175516, l='MpServer', x=159.72, y=62.00, z=-433.34], EntityCreeper['Creeper'/2198128, l='MpServer', x=87.50, y=64.00, z=-436.50], EntitySpider['Spider'/2198131, l='MpServer', x=89.50, y=64.00, z=-434.50], EntityStray['Stray'/2198133, l='MpServer', x=94.50, y=64.00, z=-430.50], EntityEnderman['Enderman'/2198135, l='MpServer', x=38.50, y=64.00, z=-524.50], EntityEnderman['Enderman'/2198136, l='MpServer', x=38.50, y=64.00, z=-526.50], EntitySpider['Spider'/2209346, l='MpServer', x=30.50, y=64.00, z=-565.50], EntityXPOrb['Experience Orb'/2184791, l='MpServer', x=134.32, y=64.00, z=-445.49], EntityXPOrb['Experience Orb'/2184792, l='MpServer', x=135.52, y=64.00, z=-447.45], EntityXPOrb['Experience Orb'/2151072, l='MpServer', x=158.89, y=64.00, z=-439.67], EntityXPOrb['Experience Orb'/2151073, l='MpServer', x=160.06, y=64.00, z=-436.34], EntityXPOrb['Experience Orb'/2203315, l='MpServer', x=113.86, y=64.00, z=-485.13], EntityXPOrb['Experience Orb'/2203314, l='MpServer', x=111.42, y=64.00, z=-483.42], EntityXPOrb['Experience Orb'/2203316, l='MpServer', x=115.00, y=64.00, z=-486.12], EntityStray['Stray'/2203324, l='MpServer', x=72.50, y=64.00, z=-461.50], EntityCreeper['Creeper'/2203327, l='MpServer', x=85.50, y=64.00, z=-458.50], EntityEnderman['Enderman'/2198153, l='MpServer', x=140.40, y=64.00, z=-514.76], EntityZombie['Zombie'/2212509, l='MpServer', x=161.95, y=64.00, z=-467.82], EntityXPOrb['Experience Orb'/2151071, l='MpServer', x=158.91, y=64.00, z=-439.58], EntityXPOrb['Experience Orb'/2205427, l='MpServer', x=99.32, y=64.00, z=-503.40], EntityStray['Stray'/2204406, l='MpServer', x=110.66, y=64.00, z=-564.59], EntityPlayerSP['TipsyBrandy'/15, l='MpServer', x=84.40, y=64.00, z=-510.01], EntitySpider['Spider'/2200257, l='MpServer', x=154.50, y=64.00, z=-540.50], EntityEnderman['Enderman'/2200261, l='MpServer', x=158.28, y=64.00, z=-547.40], EntitySpider['Spider'/2203336, l='MpServer', x=68.50, y=64.00, z=-471.50], EntityCreeper['Creeper'/2201385, l='MpServer', x=149.69, y=64.00, z=-481.86], EntityCreeper['Creeper'/2201389, l='MpServer', x=157.50, y=64.00, z=-482.50], EntityXPOrb['Experience Orb'/2144058, l='MpServer', x=180.36, y=64.00, z=-423.81], EntityXPOrb['Experience Orb'/2144059, l='MpServer', x=176.88, y=62.00, z=-418.96], EntityXPOrb['Experience Orb'/2144060, l='MpServer', x=172.30, y=64.00, z=-419.68], EntityXPOrb['Experience Orb'/2180891, l='MpServer', x=131.58, y=64.00, z=-423.52], EntityXPOrb['Experience Orb'/2180892, l='MpServer', x=131.21, y=64.00, z=-425.24], EntityVehicle['Cruiser MkVI Crusader'/1351509, l='MpServer', x=222.50, y=62.63, z=-378.50], EntitySeat['entity.Seat.name'/1351510, l='MpServer', x=222.48, y=63.75, z=-379.12], EntityWheel['entity.Wheel.name'/1351511, l='MpServer', x=223.84, y=62.00, z=-379.52], EntitySpider['Spider'/2179947, l='MpServer', x=117.50, y=64.00, z=-530.50], EntityWheel['entity.Wheel.name'/1351512, l='MpServer', x=221.63, y=62.00, z=-379.94], EntityWheel['entity.Wheel.name'/1351513, l='MpServer', x=221.16, y=62.00, z=-377.48], EntityWheel['entity.Wheel.name'/1351514, l='MpServer', x=223.37, y=62.00, z=-377.06], EntityStray['Stray'/2179950, l='MpServer', x=128.27, y=64.00, z=-523.63], EntityZombie['Zombie'/2161523, l='MpServer', x=163.17, y=64.00, z=-495.80], EntityCamera['unknown'/1351535, l='MpServer', x=222.50, y=62.63, z=-378.50], EntitySpider['Spider'/2202496, l='MpServer', x=156.50, y=64.00, z=-470.50], EntityWheel['entity.Wheel.name'/1341424, l='MpServer', x=242.75, y=60.00, z=-377.50], EntityZombie['Zombie'/2173911, l='MpServer', x=48.50, y=64.00, z=-445.50], EntityItem['item.item.string'/2203607, l='MpServer', x=118.29, y=64.00, z=-478.68], EntitySeat['entity.Seat.name'/1341420, l='MpServer', x=241.59, y=61.75, z=-379.37], EntityWheel['entity.Wheel.name'/1341421, l='MpServer', x=242.75, y=60.00, z=-380.00], EntityWheel['entity.Wheel.name'/1341422, l='MpServer', x=240.50, y=60.00, z=-380.00], EntityWheel['entity.Wheel.name'/1341423, l='MpServer', x=240.50, y=60.00, z=-377.50], EntityVehicle['Cruiser MkVI Crusader'/1341419, l='MpServer', x=241.63, y=60.62, z=-378.75]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:420)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2740)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:418)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 8.1 (amd64) version 6.3
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 692605848 bytes (660 MB) / 2113929216 bytes (2016 MB) up to 2147483648 bytes (2048 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2768 27 mods loaded, 27 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State     | ID                            | Version         | Source                                          | Signature                                |
	|:--------- |:----------------------------- |:--------------- |:----------------------------------------------- |:---------------------------------------- |
	| UCHIJAAAA | minecraft                     | 1.12.2          | minecraft.jar                                   | None                                     |
	| UCHIJAAAA | mcp                           | 9.42            | minecraft.jar                                   | None                                     |
	| UCHIJAAAA | FML                           | 8.0.99.99       | forge-1.12.2-14.23.5.2768.jar                   | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJAAAA | forge                         | 14.23.5.2768    | forge-1.12.2-14.23.5.2768.jar                   | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJAAAA | obfuscate                     | 0.2.6           | minecraft.jar                                   | None                                     |
	| UCHIJAAAA | securitycraft                 | v1.8.2.3        | [1.12]+SecurityCraft+v1.8.2.3.jar               | None                                     |
	| UCHIJAAAA | biomesoplenty                 | 7.0.1.2422      | BiomesOPlenty-1.12.2-7.0.1.2422-universal.jar   | None                                     |
	| UCHIJAAAA | cdm                           | 0.4.1           | cdm-0.4.1-mc1.12.2.jar                          | None                                     |
	| UCHIJAAAA | cfm                           | 6.2.0           | cfm-6.2.0-mc1.12.2.jar                          | None                                     |
	| UCHIJAAAA | cgm                           | 0.9.2           | cgm-0.9.2-mc1.12.2.jar                          | None                                     |
	| UCHIJAAAA | extendedrenderer              | v1.0            | CoroUtil-1.12.2.jar                             | None                                     |
	| UCHIJAAAA | coroutil                      | 1.12.1-1.2.19   | CoroUtil-1.12.2.jar                             | None                                     |
	| UCHIJAAAA | configmod                     | v1.0            | CoroUtil-1.12.2.jar                             | None                                     |
	| UCHIJAAAA | dsurround                     | 3.4.7.2         | DynamicSurroundings-1.12.2-3.4.7.2.jar          | 7a2128d395ad96ceb9d9030fbd41d035b435753a |
	| UCHIJAAAA | presets                       | 3.4.7.2         | DynamicSurroundings-1.12.2-3.4.7.2.jar          | None                                     |
	| UCHIJAAAA | flansmod                      | 5.5.2           | Flan's Mod-1.12.2-5.5.2.jar                     | None                                     |
	| UCHIJAAAA | flansmodapocalypse            | 1.0             | Flan's Mod-1.12.2-5.5.2.jar                     | None                                     |
	| UCHIJAAAA | hospital_mod__facilities_pack | 1.12.2          | Hospital-Mod-Facilities-Pack-Mod-1.12.2.jar     | None                                     |
	| UCHIJAAAA | icbmclassic                   | 1.12.2-3.3.0.63 | ICBM-classic-1.12.2-3.3.0b63.jar                | None                                     |
	| UCHIJAAAA | jei                           | 4.13.1.225      | jei_1.12.2-4.13.1.225.jar                       | None                                     |
	| UCHIJAAAA | mts                           | 12.3.0          | Minecraft+Transport+Simulator-1.12.2-12.3.0.jar | None                                     |
	| UCHIJAAAA | mtsseagullmilitarypack        | 1.4.0           | MTS+Seagull's+military+pack+1.3.0.jar           | None                                     |
	| UCHIJAAAA | mtsofficialpack               | 8.0.0           | MTS_Official_Pack_V08.jar                       | None                                     |
	| UCHIJAAAA | pointless_tech_two            | 2               | Pointless-Tech-2-Mod-1.12.2.jar                 | None                                     |
	| UCHIJAAAA | sleepingtubes                 | 1.0.0           | Sleeping-Tubes-Mod-1.12.2.zip                   | None                                     |
	| UCHIJAAAA | weather2                      | 1.12.1-2.6.12   | Weather-Storms-Tornadoes-Mod-1.12.2.jar         | None                                     |
	| UCHIJAAAA | xaerominimap                  | 1.16            | Xaeros-Minimap-Mod-1.12.jar                     | None                                     |

	Loaded coremods (and transformers): 
ObfuscatePlugin (obfuscate-0.2.6-1.12.2.jar)
  com.mrcrayfish.obfuscate.asm.ObfuscateTransformer
DynamicSurroundingsCore (DynamicSurroundings-1.12.2-3.4.7.2.jar)
  org.blockartistry.DynSurround.asm.Transformer
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 388.31' Renderer: 'GeForce GTX 1050 Ti/PCIe/SSE2'
	Launched Version: 1.12.2-forge1.12.2-14.23.5.2768
	LWJGL: 2.9.4
	OpenGL: GeForce GTX 1050 Ti/PCIe/SSE2 GL version 4.6.0 NVIDIA 388.31, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 8x AMD FX(tm)-8350 Eight-Core Processor

**Comment by Liruxo** [comment] 2019-03-08 09:46
Does this crash persist in the newest version?:
https://github.com/FlansMods/FlansMod/releases

If it does can you please add the exact version of Forge and Flan's Mod you are using, e.g. 
Forge: 14.23.5.2815 and Flan's Mod: 1.12.2-5.5.2
And as i am not able to reproduce this, please be more specific on what exactly causes the crash
Does the placing of the 'Gun Modification Table' Crash the game, or does it crash if you try to open it? Does it work if you have nothing except the 'Gun Modification Table' in the inventory?
Additionally a stack trace/crash report would be really helpful

**Comment by ChrisLane** [comment] 2019-03-08 14:44
Duplicate of #903 I suspect, update to the latest version at Liruxo's link.

**Closed as completed by ChrisLane** 2019-03-08 14:44 UTC
Labels: crash
