### ISSUE TITLE
[1.12.2] Deployable weapons have the wrong view angle

### ISSUE THREAD

**Issue by Tonas1997** [FlansMods/FlansMod#1174] opened 2020-02-20 20:58 UTC
All deployable weapons, when operated, point downwards. This makes it impossible to use them in any way whatsover - unless you _want_ to open holes on the ground:

![2020-02-20_20 56 11](https://user-images.githubusercontent.com/43859708/74978033-c261cf80-5423-11ea-8325-106a7e75eaf4.png)
![2020-02-20_20 56 22](https://user-images.githubusercontent.com/43859708/74978035-c392fc80-5423-11ea-8097-6daee558a551.png)

**Comment by ChrisLane** [comment] 2020-02-20 22:39
Duplicate of #931 #925. Not following the bug issue template. Already fixed.

**Closed as completed by ChrisLane** 2020-02-20 22:39 UTC
Labels: bug
