### ISSUE TITLE
Game crashes when opening armor box

### ISSUE THREAD

**Issue by koflin** [FlansMods/FlansMod#962] opened 2018-10-21 08:06 UTC
So when I open the armor box from the WW2 packI sometimes get this error.

AMDescription: Rendering screen

> java.lang.NullPointerException: Rendering screen
> 	at com.flansmod.client.gui.GuiArmourBox.drawRecipe(GuiArmourBox.java:122)
> 	at com.flansmod.client.gui.GuiArmourBox.func_73863_a(GuiArmourBox.java:85)
> 	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:381)
> 	at sun.reflect.GeneratedMethodAccessor54.invoke(Unknown Source)
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.lang.reflect.Method.invoke(Method.java:497)
> 	at net.optifine.reflect.Reflector.callVoid(Reflector.java:654)
> 	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1456)
> 	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1118)
> 	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:397)
> 	at net.minecraft.client.main.Main.main(SourceFile:123)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.lang.reflect.Method.invoke(Method.java:497)
> 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
> 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

**Comment by ChrisLane** [comment] 2018-10-21 09:27
Duplicate of #854 #856 #887 and #913

**Closed as completed by ChrisLane** 2018-10-21 09:27 UTC
