### ISSUE TITLE
Invisible MP40

### ISSUE THREAD

**Issue by 365Tito** [FlansMods/FlansMod#1260] opened 2020-07-18 20:55 UTC
**Describe the bug**

The MP40 is invisible. Shows up in inventory, works and shoots but doesn't show up as a 3D model.
**To Reproduce**
Steps to reproduce the behaviour:
1. Install latest version 5.6 beta 8
2. Put MP40 in inventory

**Expected behaviour**

There should be a gun...

**Screenshots**

**Versions (please complete the following information)**
 - Forge: Forge 1.12.2 
 - Flan's Mod: 5.6.beta8

**Additional context**

**Comment by Liruxo** [comment] 2020-07-19 18:11
I believe this is a duplicate of #1108

**Closed as completed** 2020-07-20 08:24 UTC
Labels: bug
