### ISSUE TITLE
planes guns not working

### ISSUE THREAD

**Issue by solslinger55** [FlansMods/FlansMod#957] opened 2018-10-12 17:21 UTC
i put in the right ammo and it doesnt shoot i dont know why but i have a server for it and my friends want me to fix it so can someone tell me why its not working?

**Comment by DerScherenmann** [comment] 2018-10-13 13:11
Are your keybinds correct and not interferired by other mods?

**Comment by solslinger55** [comment] 2018-10-14 01:34
yes i made sure of it.

**Comment by ChrisLane** [comment] 2018-11-02 13:18
Duplicate of #910

**Closed as completed by ChrisLane** 2018-11-02 13:18 UTC
