### ISSUE TITLE
Galacticraft <--> Flans mod incompatibility

### ISSUE THREAD

**Issue by Meesmaalt** [FlansMods/FlansMod#1021] opened 2019-03-13 09:11 UTC
**To Reproduce**
Steps to reproduce the crash:
1. install flans mod 5.5.2
2. install galacticraft; galacticraft planets; micdoodleCore mods for 1.12.2
3. Launch them on forge 1.12 2800>

**Screenshots**
no point

**Versions (please complete the following information):**
 - Forge: 14.23.5.2815
 - Flan's Mod: 5.5.2

**Additional context**
The game crashed whilst there was a severe problem during mod loading that has caused the game to fail
Error: net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Flan's Mod: Apocalypse (flansmodapocalypse)

Please fix

**Comment by ChrisLane** [comment] 2019-03-13 09:39
Looks like a duplicate of #992, please use the issues search function before posting a new issue.

**Closed as completed by ChrisLane** 2019-03-13 09:39 UTC
Labels: crash
