### ISSUE TITLE
Aircraft Forward-Firing Armament Won't Fire.

### ISSUE THREAD

**Issue by CaveMiner1215** [FlansMods/FlansMod#966] opened 2018-11-02 12:27 UTC
This has been posted before, but I haven't seen a definitive developer response on the issue, so I'm making a more formalized report.  No matter what I do, aircraft forward-firing armament won't fire.  I loaded the correct ammunition into the guns, and nothing happens when I left click (which is how I'm supposed to fire, I presume).  I've even tried using the "Gun Key", but I'm not really sure what it does.

This was tested with the Bf 109.

Another thing I've found is that machine guns on tanks won't fire either.

Flans and Content Pack version: 5.6
Forge Version: 14.23.4.2765

**Note:** This was done in a modpack, but it lacks Malisis Doors and its core mod

**Comment by ChrisLane** [comment] 2018-11-02 13:18
I'm aware of the issue, I just haven't tackled it yet.
Duplicate of #910.

**Closed as completed by ChrisLane** 2018-11-02 13:18 UTC
