### ISSUE TITLE
Game crashed when I shot a NPC plane in the apocalypes

### ISSUE THREAD

**Issue by gigiandearl** [FlansMods/FlansMod#807] opened 2016-04-03 15:29 UTC
so I saw a plane flying by itself in the apocalypses, and I shot it with a bazooka, as soon as it hit minecraft crashed with this error message.

---- Minecraft Crash Report ----

WARNING: coremods are present:
  FMLPlugin (InventoryTweaks-1.59-176.jar)
  CCLCorePlugin (CodeChickenLib-1.8-1.1.2.133-universal.jar)
  CodeChickenCorePlugin (CodeChickenCore-1.8-1.0.5.36-universal.jar)
  CCCDeobfPlugin (unknown)
  NEICorePlugin (NotEnoughItems-1.8-1.0.5.104-universal.jar)
Contact their authors BEFORE contacting forge

// On the bright side, I bought you a teddy bear!

Time: 03/04/16 11:25 AM
Description: Ticking entity

java.lang.NullPointerException: Ticking entity
	at com.flansmod.common.driveables.DriveableType.getItemsRequired(DriveableType.java:545)
	at com.flansmod.common.driveables.PlaneType.getItemsRequired(PlaneType.java:172)
	at com.flansmod.common.driveables.EntityDriveable.killPart(EntityDriveable.java:1246)
	at com.flansmod.common.driveables.EntityDriveable.checkParts(EntityDriveable.java:1202)
	at com.flansmod.common.driveables.EntityDriveable.bulletHit(EntityDriveable.java:1162)
	at com.flansmod.common.guns.EntityBullet.func_70071_h_(EntityBullet.java:415)
	at net.minecraft.world.World.func_72866_a(World.java:1880)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:732)
	at net.minecraft.world.World.func_72870_g(World.java:1850)
	at net.minecraft.world.World.func_72939_s(World.java:1679)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:571)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:704)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:598)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:258)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:478)
	at java.lang.Thread.run(Thread.java:745)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at com.flansmod.common.driveables.DriveableType.getItemsRequired(DriveableType.java:545)
	at com.flansmod.common.driveables.PlaneType.getItemsRequired(PlaneType.java:172)
	at com.flansmod.common.driveables.EntityDriveable.killPart(EntityDriveable.java:1246)
	at com.flansmod.common.driveables.EntityDriveable.checkParts(EntityDriveable.java:1202)
	at com.flansmod.common.driveables.EntityDriveable.bulletHit(EntityDriveable.java:1162)
	at com.flansmod.common.guns.EntityBullet.func_70071_h_(EntityBullet.java:415)
	at net.minecraft.world.World.func_72866_a(World.java:1880)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:732)
	at net.minecraft.world.World.func_72870_g(World.java:1850)

-- Entity being ticked --
Details:
	Entity Type: flansmod.Bullet (com.flansmod.common.guns.EntityBullet)
	Entity ID: 1342983
	Entity Name: entity.flansmod.Bullet.name
	Entity's Exact location: 2862.06, 118.89, -2010.29
	Entity's Block location: 2862.00,118.00,-2011.00 - World: (2862,118,-2011), Chunk: (at 14,7,5 in 178,-126; contains blocks 2848,0,-2016 to 2863,255,-2001), Region: (5,-4; contains chunks 160,-128 to 191,-97, blocks 2560,0,-2048 to 3071,255,-1537)
	Entity's Momentum: 3.46, 0.69, 2.74
	Entity's Rider: ~~ERROR~~ NullPointerException: null
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1679)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:571)

-- Affected level --
Details:
	Level name: Spencer's apoc
	All players: 1 total; [EntityPlayerMP['Gigiandearl'/1230327, l='Spencer's apoc', x=2822.02, y=109.00, z=-2041.94]]
	Chunk stats: ServerChunkCache: 453 Drop: 0
	Level seed: -5807803794108449539
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: 0.00,0.00,0.00 - World: (0,0,0), Chunk: (at 0,0,0 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 0 game time, 0 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:704)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:598)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:258)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:478)
	at java.lang.Thread.run(Thread.java:745)

-- System Details --
Details:
	Minecraft Version: 1.8
	Operating System: Linux (amd64) version 4.2.0-34-generic
	Java Version: 1.8.0_77, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 510473600 bytes (486 MB) / 1155670016 bytes (1102 MB) up to 3207856128 bytes (3059 MB)
	JVM Flags: 5 total; -Xmx3G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	IntCache: cache: 0, tcache: 0, allocated: 1, tallocated: 12
	FML: MCP v9.10 FML v8.0.99.99 Minecraft Forge 11.14.4.1563 Optifine OptiFine_1.8_HD_U_D5 9 mods loaded, 9 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAAAAAAAAAAAAAAAAAAAAAA	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAAAAAAAAAAAAAAAAAAAAAA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.8-11.14.4.1563.jar) 
	UCHIJAAAAAAAAAAAAAAAAAAAAAAAA	Forge{11.14.4.1563} [Minecraft Forge] (forge-1.8-11.14.4.1563.jar) 
	UCHIJAAAAAAAAAAAAAAAAAAAAAAAA	CodeChickenCore{1.0.5.36} [CodeChicken Core] (minecraft.jar) 
	UCHIJAAAAAAAAAAAAAAAAAAAAAAAA	NotEnoughItems{1.0.5.104} [Not Enough Items] (NotEnoughItems-1.8-1.0.5.104-universal.jar) 
	UCHIJAAAAAAAAAAAAAAAAAAAAAAAA	flansmod{5.1} [Flan's Mod] (Flan's Mod-1.8-5.1.jar) 
	UCHIJAAAAAAAAAAAAAAAAAAAAAAAA	flansmodapocalypse{1.0} [Flan's Mod: Apocalypse] (Flan's Mod Apocalypse-1.8-1.0.jar) 
	UCHIJAAAAAAAAAAAAAAAAAAAAAAAA	inventorytweaks{1.59-176-9318a76-dirty} [Inventory Tweaks] (InventoryTweaks-1.59-176.jar) 
	UCHIJAAAAAAAAAAAAAAAAAAAAAAAA	MapWriter{2.2.5} [MapWriter] (MapWriter-1.8-2.2.5.jar) 
	Loaded coremods (and transformers): 
FMLPlugin (InventoryTweaks-1.59-176.jar)
  invtweaks.forge.asm.ContainerTransformer
CCLCorePlugin (CodeChickenLib-1.8-1.1.2.133-universal.jar)
  codechicken.lib.asm.ClassHeirachyManager
  codechicken.lib.asm.RenderHookTransformer
CodeChickenCorePlugin (CodeChickenCore-1.8-1.0.5.36-universal.jar)
  codechicken.core.asm.InterfaceDependancyTransformer
  codechicken.core.asm.TweakTransformer
  codechicken.core.asm.DelegatedTransformer
  codechicken.core.asm.DefaultImplementationTransformer
CCCDeobfPlugin (unknown)
  
NEICorePlugin (NotEnoughItems-1.8-1.0.5.104-universal.jar)
  codechicken.nei.asm.NEITransformer
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	Profiler Position: N/A (disabled)
	Player Count: 1 / 8; [EntityPlayerMP['Gigiandearl'/1230327, l='Spencer's apoc', x=2822.02, y=109.00, z=-2041.94]]
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'

**Comment by ChrisLane** [comment] 2016-06-27 00:49
Dupe of #786

**Closed by ChrisLane** 2016-06-27 00:49 UTC
