### ISSUE TITLE
Flans mod doesnt let me drop bombs from my vehicles or shoot

### ISSUE THREAD

**Issue by CTmatey** [FlansMods/FlansMod#950] opened 2018-09-10 08:10 UTC
the helicopters and the planes dont shoot or drop bombs why? i have the right ammo

**Comment by IvorAmlug** [comment] 2018-09-17 12:33
is Massilis Doors installed ?

**Comment by IvorAmlug** [comment] 2018-09-17 14:35
It has issues with flans

**Comment by solslinger55** [comment] 2018-10-12 17:35
i have the same problem but only the planes dont work and i can drop bombs

**Comment by CTmatey** [comment] 2018-10-16 06:44
i will check

**Comment by CTmatey** [comment] 2018-10-16 06:46
no is it meant to be?

**Comment by IvorAmlug** [comment] 2018-10-16 10:31
No its most time the case of the error any other massilis mod?

**Comment by CTmatey** [comment] 2018-10-17 00:30
Ok thanks anyways

**Comment by ChrisLane** [comment] 2018-11-02 13:19
Duplicate of #910

**Closed as completed by ChrisLane** 2018-11-02 13:19 UTC
