### ISSUE TITLE
Sentry Gun causes game/server to time out

### ISSUE THREAD

**Issue by Matcha7** [FlansMods/FlansMod#1184] opened 2020-03-26 08:29 UTC
**Describe the bug**
Upon placing down the sentry gun, the sentry gun is frozen (does not aim/shoot at nearby mobs). Everything in the game freezes (mobs freeze), but player can still move. In singleplayer, nothing gets saved after that and in multiplayer, the server times out/crashes.

**To Reproduce**
Steps to reproduce the behaviour:
1. Place down a sentry gun

**Expected behaviour**
Singleplayer: mobs freeze, player can still move, but if you try to save, the game crashes/freezes
Multiplayer: mobs freeze, player can still move, server times out after a while and pauses/crashes.

**Screenshots**

**Versions (please complete the following information)**
 - Forge: 1.12.2 - 14.23.5.2768
 - Flan's Mod: v5.6-beta.6

**Additional context**

**Comment by Liruxo** [comment] 2020-04-24 16:50
I am unable to reproduce these results.
Please verify you are using the latest content packs and FlansMod jar. If the issue persists it is recommended to use a fresh Minecraft, Forge and FlansMod installation to rule out outdated or faulty jars and/or configuration files
Please also verify you are following [these steps](https://github.com/FlansMods/FlansMod/wiki/Installing-FlansMod) to install FlansMod, if not note the differences to your process

**Comment by Liruxo** [comment] 2020-04-24 19:02
I was unable to reproduce the issue with the steps provided, however i did encounter an issue while using Sentry guns which lead to the problems described here
The problems are fixed in  #1197

**Comment by ChrisLane** [comment] 2020-05-08 12:32
@Matcha7 please let us know if you are still able to reproduce this in v5.6-beta.7. Closing until then.

**Closed as completed by ChrisLane** 2020-05-08 12:32 UTC
Labels: bug
