### ISSUE TITLE
No Cooldown on tanks ( atleast on Chi-Nu )

### ISSUE THREAD

**Issue by rvveber** [FlansMods/FlansMod#1245] opened 2020-06-15 20:52 UTC
So i only tested this with 2 tanks and one did have the problem the other did not.
Which means the bug seems to be tank specific.

1. Spawn the Chi-Nu.
2. Fill it up with shells.
3. ( shooting is set to left click in my config - not sure if that matters )
4. Between each leftclick, do a rightclick.
5. This will cancel the reload cooldown and on the next leftclick a projectile is fired
6. You can even go full laserbeam with this if you hold leftclick and than hold rightclick.

**Versions (please complete the following information)**
 - Forge 14.23.5.2854
 - Flan.s.Mod-1.12.2-5.6.0-beta.8.jar

Also i have a question, where is the damage of the tanks defined?
I couldn't find a config other than `DamageModifierPrimary` and even tanks that did have that config changing it did do absolutely nothing. Tanks are currently far too strong, they one or two hit even big tanks. That should be balanced or atleast made balancable.

**Comment by matt-bel** [comment] 2020-06-28 01:17
This must be yet another bug caused by the controls revamp.

**Comment by matt-bel** [comment] 2020-07-04 19:38
My pull request makes a fix for this color-space

**Comment by DubTheGrub** [comment] 2020-07-12 05:04
I've actually managed to recreate this with the Char Bis

**Comment by rvveber** [comment] 2020-07-14 12:29
@hereami321 tried to fix this in commit a2594eddfa5acb866dee0d7fc7bbd270523b91e5

**Closed as completed** 2020-07-25 21:11 UTC
Labels: bug
